<?php
declare(strict_types=1);
require dirname(__DIR__) . '/vendor/autoload.php';
use Wellness\Service\CustomerOnboarding as C;
use Wellness\Http\ApiException;
$checks=0;
$assert=function(bool $ok) use(&$checks) { if(!$ok) throw new RuntimeException('Onboarding assertion failed'); $checks++; };
$reject=function(callable $fn) use($assert) { try{$fn();}catch(ApiException){$assert(true);return;} throw new RuntimeException('Unsafe input accepted'); };
$now=time(); $stamp=fn(int $n)=>gmdate('Y-m-d H:i:s',$n);
$access=['iss'=>'trusted','sub'=>'subject','oid'=>'11111111-1111-1111-1111-111111111111','tid'=>'tenant'];
$proof=$access+['auth_time'=>$now];
$challenge=['created_at'=>$stamp($now-10),'expires_at'=>$stamp($now+600),'consumed_at'=>null];
C::validateFreshProof($access,$proof,$challenge,$now); $assert(true);
foreach(['oid'=>'22222222-2222-2222-2222-222222222222','tid'=>'other','auth_time'=>$now-601] as $k=>$v) $reject(fn()=>C::validateFreshProof($access,array_replace($proof,[$k=>$v]),$challenge,$now));
foreach([null,(string)$now,$now+61] as $v) $reject(fn()=>C::validateFreshProof($access,array_replace($proof,['auth_time'=>$v]),$challenge,$now));
foreach([['consumed_at'=>$stamp($now)],['expires_at'=>$stamp($now)],['created_at'=>$stamp($now+61)]] as $v) $reject(fn()=>C::validateFreshProof($access,$proof,array_replace($challenge,$v),$now));
$session=['revoked_at'=>null,'expires_at'=>$stamp($now+28800),'last_activity_at'=>$stamp($now)];
$assert(C::sessionIsActive($session,$now+1799));
$assert(!C::sessionIsActive($session,$now+1800));
$assert(!C::sessionIsActive(array_replace($session,['last_activity_at'=>$stamp($now+28800)]),$now+28800));
$assert(!C::sessionIsActive(array_replace($session,['revoked_at'=>$stamp($now)]),$now));
$assert(C::identityHash($access)!==C::identityHash(array_replace($access,['sub'=>'Subject'])));
$assert(C::identityHash($access)===C::identityHash($access+['email'=>'someone@example.test']));
$body=['given_name'=>'Test','family_name'=>'Client','email'=>'test@example.test','phone'=>'555-0100','address'=>['address_line1'=>'1 Test Street','city'=>'Test City','province'=>'ON','postal_code'=>'A1A 1A1','country'=>'Canada']];
$assert(C::profileInput($body)['phone']==='555-0100');
foreach(['clinic_id'=>2,'user_id'=>1,'roles'=>['super_admin'],'administrative_notes'=>'private','date_of_birth'=>'2000-01-01','status'=>'active'] as $k=>$v) $reject(fn()=>C::profileInput($body+[$k=>$v]));
$reject(fn()=>C::profileInput(array_replace($body,['phone'=>''])));
$reject(fn()=>C::profileInput(array_replace($body,['address'=>[]])));
echo "$checks onboarding policy checks passed.\n";
