-- Wellness Centre Scheduling Platform - MySQL 8.0+
-- Store DATETIME values in UTC; convert using locations.timezone at the API boundary.
CREATE DATABASE IF NOT EXISTS wellness_centre CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE wellness_centre;
SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- Organization, identity, and access
CREATE TABLE clinics (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,legal_name VARCHAR(190),email VARCHAR(190),phone VARCHAR(40),status ENUM('active','inactive') NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE locations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,timezone VARCHAR(64) NOT NULL DEFAULT 'America/Toronto',address_line1 VARCHAR(190),address_line2 VARCHAR(190),city VARCHAR(100),province VARCHAR(80),postal_code VARCHAR(20),phone VARCHAR(40),is_bookable BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_location_name(clinic_id,name),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,email VARCHAR(190) NOT NULL,display_name VARCHAR(150) NOT NULL,given_name VARCHAR(100),family_name VARCHAR(100),user_type ENUM('client','staff') NOT NULL,status ENUM('pending','active','locked','inactive') NOT NULL DEFAULT 'pending',last_login_at DATETIME,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_user_email(clinic_id,email),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE identity_links (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,provider ENUM('microsoft','google','meta','internal') NOT NULL,tenant_id VARCHAR(64),tenant_key VARCHAR(64) GENERATED ALWAYS AS (COALESCE(tenant_id,'')) STORED,provider_subject VARCHAR(191) NOT NULL COMMENT 'Immutable oid/sub from provider',email_at_link_time VARCHAR(190),created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_provider_identity(provider,tenant_key,provider_subject),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(50) NOT NULL UNIQUE,name VARCHAR(100) NOT NULL,description VARCHAR(500)) ENGINE=InnoDB;
CREATE TABLE user_roles (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,role_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NULL COMMENT 'NULL is clinic-wide',location_scope BIGINT UNSIGNED GENERATED ALWAYS AS (COALESCE(location_id,0)) STORED,assigned_by BIGINT UNSIGNED,assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_role_scope(user_id,role_id,location_scope),FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(role_id) REFERENCES roles(id),FOREIGN KEY(location_id) REFERENCES locations(id),FOREIGN KEY(assigned_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE staff_accounts (user_id BIGINT UNSIGNED PRIMARY KEY,password_hash VARCHAR(255) COMMENT 'Only for optional internal login; use Argon2id',failed_login_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,locked_until DATETIME,mfa_required BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE user_profile_images (user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,mime_type VARCHAR(40) NOT NULL,image_data MEDIUMBLOB NOT NULL,byte_size INT UNSIGNED NOT NULL,content_hash CHAR(64) NOT NULL,updated_by BIGINT UNSIGNED NULL,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB;
CREATE TABLE client_profiles (user_id BIGINT UNSIGNED PRIMARY KEY,phone VARCHAR(40),preferred_contact ENUM('email','phone','sms') NOT NULL DEFAULT 'email',date_of_birth DATE,emergency_contact_name VARCHAR(150),emergency_contact_phone VARCHAR(40),administrative_notes TEXT,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;

-- Practitioners, services, and rooms
CREATE TABLE practitioners (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,discipline VARCHAR(100) NOT NULL,biography TEXT,credentials VARCHAR(500),booking_mode ENUM('practitioner_managed','clinic_managed') NOT NULL DEFAULT 'clinic_managed',contact_preferences JSON,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_practitioner_user(user_id),FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE practitioner_locations (practitioner_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(practitioner_id,location_id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE rooms (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,location_id BIGINT UNSIGNED NOT NULL,name VARCHAR(100) NOT NULL,room_type VARCHAR(80),equipment_notes TEXT,turnover_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,is_bookable BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_room_name(location_id,name),FOREIGN KEY(location_id) REFERENCES locations(id)) ENGINE=InnoDB;
CREATE TABLE room_capabilities (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,code VARCHAR(80) NOT NULL,name VARCHAR(120) NOT NULL,UNIQUE KEY uq_capability_code(clinic_id,code),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE room_capability_assignments (room_id BIGINT UNSIGNED NOT NULL,capability_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(room_id,capability_id),FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE,FOREIGN KEY(capability_id) REFERENCES room_capabilities(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE service_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,name VARCHAR(120) NOT NULL,description VARCHAR(500),UNIQUE KEY uq_service_category(clinic_id,name),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE services (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,category_id BIGINT UNSIGNED,name VARCHAR(150) NOT NULL,description TEXT,preparation_instructions TEXT,price_cents INT UNSIGNED NOT NULL,tax_code VARCHAR(40),duration_mode ENUM('fixed','selectable') NOT NULL DEFAULT 'fixed',lead_time_minutes INT UNSIGNED NOT NULL DEFAULT 0,booking_horizon_days SMALLINT UNSIGNED NOT NULL DEFAULT 365,cancellation_window_minutes INT UNSIGNED NOT NULL DEFAULT 1440,cancellation_fee_type ENUM('none','fixed','percentage') NOT NULL DEFAULT 'none',cancellation_fee_value INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Cents or percentage basis points',buffer_before_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,buffer_after_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,requires_room BOOLEAN NOT NULL DEFAULT TRUE,recurrence_allowed BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_service_name(clinic_id,name),FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(category_id) REFERENCES service_categories(id),CHECK(buffer_before_minutes % 15=0),CHECK(buffer_after_minutes % 15=0)) ENGINE=InnoDB;
CREATE TABLE service_duration_options (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,service_id BIGINT UNSIGNED NOT NULL,duration_minutes SMALLINT UNSIGNED NOT NULL,price_cents INT UNSIGNED,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_service_duration(service_id,duration_minutes),FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE,CHECK(duration_minutes>0 AND duration_minutes % 15=0)) ENGINE=InnoDB;
CREATE TABLE practitioner_services (practitioner_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED NOT NULL,price_override_cents INT UNSIGNED,active BOOLEAN NOT NULL DEFAULT TRUE,offers_mobile BOOLEAN NOT NULL DEFAULT FALSE,mobile_radius_km SMALLINT UNSIGNED,travel_buffer_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 0,mobile_fee_cents INT UNSIGNED NOT NULL DEFAULT 0,PRIMARY KEY(practitioner_id,service_id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE service_locations (service_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(service_id,location_id),FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE,FOREIGN KEY(location_id) REFERENCES locations(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE service_room_capability_requirements (service_id BIGINT UNSIGNED NOT NULL,capability_id BIGINT UNSIGNED NOT NULL,PRIMARY KEY(service_id,capability_id),FOREIGN KEY(service_id) REFERENCES services(id) ON DELETE CASCADE,FOREIGN KEY(capability_id) REFERENCES room_capabilities(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE room_practitioner_restrictions (room_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED NOT NULL,allowed BOOLEAN NOT NULL DEFAULT TRUE,PRIMARY KEY(room_id,practitioner_id),FOREIGN KEY(room_id) REFERENCES rooms(id) ON DELETE CASCADE,FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE) ENGINE=InnoDB;

-- Scheduling
CREATE TABLE availability_rules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,practitioner_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,weekday TINYINT UNSIGNED NOT NULL COMMENT '1=Monday, 7=Sunday',start_time TIME NOT NULL,end_time TIME NOT NULL,valid_from DATE NOT NULL,valid_until DATE,recurrence_interval_weeks TINYINT UNSIGNED NOT NULL DEFAULT 1,active BOOLEAN NOT NULL DEFAULT TRUE,FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,FOREIGN KEY(location_id) REFERENCES locations(id),CHECK(weekday BETWEEN 1 AND 7),CHECK(start_time<end_time)) ENGINE=InnoDB;
CREATE TABLE availability_overrides (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,practitioner_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,override_type ENUM('available','blocked') NOT NULL,reason VARCHAR(500),created_by BIGINT UNSIGNED NOT NULL,FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,FOREIGN KEY(location_id) REFERENCES locations(id),FOREIGN KEY(created_by) REFERENCES users(id),CHECK(starts_at<ends_at)) ENGINE=InnoDB;
CREATE TABLE time_off (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,practitioner_id BIGINT UNSIGNED NOT NULL,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,reason_type ENUM('vacation','sick','personal','other') NOT NULL,notes VARCHAR(500),created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE,FOREIGN KEY(created_by) REFERENCES users(id),CHECK(starts_at<ends_at)) ENGINE=InnoDB;
CREATE TABLE imported_calendar_entries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,practitioner_id BIGINT UNSIGNED NOT NULL,source VARCHAR(80) NOT NULL,external_id VARCHAR(191),title VARCHAR(190),starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,blocks_booking BOOLEAN NOT NULL DEFAULT TRUE,imported_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_imported_event(practitioner_id,source,external_id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE recurring_series (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED NOT NULL,frequency ENUM('weekly','biweekly','monthly') NOT NULL,interval_count SMALLINT UNSIGNED NOT NULL DEFAULT 1,series_start DATE NOT NULL,series_end DATE,occurrence_limit SMALLINT UNSIGNED,status ENUM('active','completed','canceled') NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id),FOREIGN KEY(service_id) REFERENCES services(id)) ENGINE=InnoDB;
CREATE TABLE appointments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,client_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED NOT NULL,duration_option_id BIGINT UNSIGNED,room_id BIGINT UNSIGNED,recurring_series_id BIGINT UNSIGNED,starts_at DATETIME NOT NULL,ends_at DATETIME NOT NULL,buffer_starts_at DATETIME NOT NULL,buffer_ends_at DATETIME NOT NULL,status ENUM('draft','requested','confirmed','rescheduled','canceled_by_client','canceled_by_clinic','no_show','completed','invoiced','paid') NOT NULL DEFAULT 'draft',source ENUM('public','reception','practitioner','admin','import') NOT NULL,client_notes VARCHAR(1000),idempotency_key VARCHAR(100),version INT UNSIGNED NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_appointment_idempotency(clinic_id,idempotency_key),INDEX ix_practitioner_schedule(practitioner_id,buffer_starts_at,buffer_ends_at,status),INDEX ix_room_schedule(room_id,buffer_starts_at,buffer_ends_at,status),INDEX ix_client_schedule(client_id,starts_at,status),FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(location_id) REFERENCES locations(id),FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id),FOREIGN KEY(service_id) REFERENCES services(id),FOREIGN KEY(duration_option_id) REFERENCES service_duration_options(id),FOREIGN KEY(room_id) REFERENCES rooms(id),FOREIGN KEY(recurring_series_id) REFERENCES recurring_series(id),FOREIGN KEY(created_by) REFERENCES users(id),CHECK(starts_at<ends_at),CHECK(buffer_starts_at<=starts_at AND buffer_ends_at>=ends_at)) ENGINE=InnoDB;
CREATE TABLE appointment_attendees (appointment_id BIGINT UNSIGNED NOT NULL,user_id BIGINT UNSIGNED NOT NULL,attendee_type ENUM('client','guest','interpreter','guardian') NOT NULL,PRIMARY KEY(appointment_id,user_id),FOREIGN KEY(appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,FOREIGN KEY(user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE appointment_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,appointment_id BIGINT UNSIGNED NOT NULL,from_status VARCHAR(40),to_status VARCHAR(40) NOT NULL,actor_user_id BIGINT UNSIGNED,reason VARCHAR(1000),fee_triggered_cents INT UNSIGNED NOT NULL DEFAULT 0,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id) ON DELETE CASCADE,FOREIGN KEY(actor_user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE cancellation_adjustments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,appointment_id BIGINT UNSIGNED NOT NULL,original_fee_cents INT UNSIGNED NOT NULL,adjusted_fee_cents INT UNSIGNED NOT NULL,reason VARCHAR(500) NOT NULL,authorized_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(authorized_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE waitlist_entries (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,location_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED,earliest_date DATE NOT NULL,latest_date DATE,preferred_weekdays JSON,preferred_time_start TIME,preferred_time_end TIME,status ENUM('active','offered','booked','expired','removed') NOT NULL DEFAULT 'active',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(location_id) REFERENCES locations(id),FOREIGN KEY(service_id) REFERENCES services(id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id)) ENGINE=InnoDB;
CREATE TABLE waitlist_offers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,waitlist_entry_id BIGINT UNSIGNED NOT NULL,offered_starts_at DATETIME NOT NULL,expires_at DATETIME NOT NULL,status ENUM('pending','accepted','declined','expired') NOT NULL DEFAULT 'pending',appointment_id BIGINT UNSIGNED,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(waitlist_entry_id) REFERENCES waitlist_entries(id) ON DELETE CASCADE,FOREIGN KEY(appointment_id) REFERENCES appointments(id)) ENGINE=InnoDB;

-- Forms and clinical records
CREATE TABLE form_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,owner_practitioner_id BIGINT UNSIGNED,name VARCHAR(190) NOT NULL,form_type ENUM('intake','consent','follow_up','questionnaire') NOT NULL,version INT UNSIGNED NOT NULL DEFAULT 1,definition JSON NOT NULL COMMENT 'Published versions are immutable',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(owner_practitioner_id) REFERENCES practitioners(id)) ENGINE=InnoDB;
CREATE TABLE form_assignments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,form_template_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED,service_id BIGINT UNSIGNED,required BOOLEAN NOT NULL DEFAULT TRUE,due_minutes_before INT UNSIGNED,FOREIGN KEY(form_template_id) REFERENCES form_templates(id) ON DELETE CASCADE,FOREIGN KEY(practitioner_id) REFERENCES practitioners(id),FOREIGN KEY(service_id) REFERENCES services(id),CHECK(practitioner_id IS NOT NULL OR service_id IS NOT NULL)) ENGINE=InnoDB;
CREATE TABLE form_submissions (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,form_template_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED,client_id BIGINT UNSIGNED NOT NULL,response_data JSON NOT NULL,status ENUM('draft','submitted','reviewed','amended') NOT NULL DEFAULT 'draft',submitted_at DATETIME,reviewed_by BIGINT UNSIGNED,reviewed_at DATETIME,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(form_template_id) REFERENCES form_templates(id),FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(reviewed_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE practitioner_client_notes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,practitioner_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED,note_text TEXT NOT NULL,releasability ENUM('review_required','releasable','restricted_by_law') NOT NULL DEFAULT 'review_required',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,INDEX ix_notes_access(practitioner_id,client_id),FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(practitioner_id) REFERENCES practitioners(id),FOREIGN KEY(appointment_id) REFERENCES appointments(id)) ENGINE=InnoDB;

-- Notifications and operational work
CREATE TABLE notification_templates (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,event_code VARCHAR(80) NOT NULL,channel ENUM('email','sms') NOT NULL DEFAULT 'email',subject_template VARCHAR(255),body_template TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_notification_template(clinic_id,event_code,channel),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE reminder_schedules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,event_code VARCHAR(80) NOT NULL DEFAULT 'appointment_reminder',minutes_before INT UNSIGNED NOT NULL,channel ENUM('email','sms') NOT NULL DEFAULT 'email',active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_reminder_schedule(clinic_id,event_code,minutes_before,channel),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE notification_events (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED,recipient_user_id BIGINT UNSIGNED,recipient_address VARCHAR(190) NOT NULL,event_code VARCHAR(80) NOT NULL,channel ENUM('email','sms') NOT NULL,status ENUM('queued','sending','sent','delivered','failed','canceled') NOT NULL DEFAULT 'queued',scheduled_at DATETIME NOT NULL,sent_at DATETIME,provider_message_id VARCHAR(191),attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,last_error VARCHAR(1000),payload JSON,INDEX ix_notification_queue(status,scheduled_at),FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(recipient_user_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE operational_tasks (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED,assigned_to BIGINT UNSIGNED,task_type VARCHAR(80) NOT NULL,title VARCHAR(190) NOT NULL,due_at DATETIME,status ENUM('open','in_progress','completed','canceled') NOT NULL DEFAULT 'open',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(appointment_id) REFERENCES appointments(id),FOREIGN KEY(assigned_to) REFERENCES users(id)) ENGINE=InnoDB;

-- Billing and accounting
CREATE TABLE taxes (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,code VARCHAR(40) NOT NULL,name VARCHAR(100) NOT NULL,rate_basis_points INT UNSIGNED NOT NULL COMMENT '1300 = 13.00%',active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_tax_code(clinic_id,code),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE clinic_booking_settings (clinic_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,default_lead_time_minutes INT UNSIGNED NOT NULL DEFAULT 60,default_booking_horizon_days SMALLINT UNSIGNED NOT NULL DEFAULT 90,default_cancellation_window_minutes INT UNSIGNED NOT NULL DEFAULT 1440,slot_increment_minutes SMALLINT UNSIGNED NOT NULL DEFAULT 15,currency CHAR(3) NOT NULL DEFAULT 'CAD',updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(clinic_id) REFERENCES clinics(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE invoices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,client_id BIGINT UNSIGNED NOT NULL,appointment_id BIGINT UNSIGNED,invoice_number VARCHAR(40) NOT NULL,status ENUM('draft','issued','partially_paid','paid','void','refunded') NOT NULL DEFAULT 'draft',currency CHAR(3) NOT NULL DEFAULT 'CAD',subtotal_cents INT UNSIGNED NOT NULL,tax_cents INT UNSIGNED NOT NULL DEFAULT 0,total_cents INT UNSIGNED NOT NULL,balance_cents INT UNSIGNED NOT NULL,issued_at DATETIME,due_at DATETIME,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_invoice_number(clinic_id,invoice_number),FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(appointment_id) REFERENCES appointments(id)) ENGINE=InnoDB;
CREATE TABLE invoice_line_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,invoice_id BIGINT UNSIGNED NOT NULL,service_id BIGINT UNSIGNED,description VARCHAR(255) NOT NULL,quantity DECIMAL(10,2) NOT NULL DEFAULT 1,unit_price_cents INT NOT NULL,tax_id BIGINT UNSIGNED,tax_cents INT NOT NULL DEFAULT 0,line_total_cents INT NOT NULL,FOREIGN KEY(invoice_id) REFERENCES invoices(id) ON DELETE CASCADE,FOREIGN KEY(service_id) REFERENCES services(id),FOREIGN KEY(tax_id) REFERENCES taxes(id)) ENGINE=InnoDB;
CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,invoice_id BIGINT UNSIGNED NOT NULL,amount_cents INT UNSIGNED NOT NULL,currency CHAR(3) NOT NULL DEFAULT 'CAD',method ENUM('cash','debit','credit','etransfer','insurance','other') NOT NULL,status ENUM('pending','completed','failed','partially_refunded','refunded') NOT NULL DEFAULT 'completed',external_reference VARCHAR(191),idempotency_key VARCHAR(100),paid_at DATETIME NOT NULL,recorded_by BIGINT UNSIGNED NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_payment_idempotency(idempotency_key),FOREIGN KEY(invoice_id) REFERENCES invoices(id),FOREIGN KEY(recorded_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE refunds (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,payment_id BIGINT UNSIGNED NOT NULL,amount_cents INT UNSIGNED NOT NULL,reason VARCHAR(500) NOT NULL,status ENUM('pending','completed','failed') NOT NULL DEFAULT 'completed',external_reference VARCHAR(191),processed_by BIGINT UNSIGNED NOT NULL,processed_at DATETIME NOT NULL,FOREIGN KEY(payment_id) REFERENCES payments(id),FOREIGN KEY(processed_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE accounting_connections (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,provider ENUM('quickbooks_online') NOT NULL,realm_id VARCHAR(191),encrypted_credentials MEDIUMBLOB COMMENT 'Encrypt outside DB with a managed key',status ENUM('disconnected','connected','expired','error') NOT NULL DEFAULT 'disconnected',connected_at DATETIME,UNIQUE KEY uq_accounting_provider(clinic_id,provider),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE accounting_mappings (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,connection_id BIGINT UNSIGNED NOT NULL,entity_type ENUM('client','service','tax') NOT NULL,internal_id BIGINT UNSIGNED NOT NULL,external_id VARCHAR(191) NOT NULL,UNIQUE KEY uq_accounting_mapping(connection_id,entity_type,internal_id),FOREIGN KEY(connection_id) REFERENCES accounting_connections(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE accounting_sync_records (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,connection_id BIGINT UNSIGNED NOT NULL,entity_type ENUM('client','invoice','payment','refund') NOT NULL,internal_id BIGINT UNSIGNED NOT NULL,external_id VARCHAR(191),direction ENUM('push','pull') NOT NULL DEFAULT 'push',status ENUM('pending','processing','succeeded','failed','needs_reconciliation') NOT NULL DEFAULT 'pending',attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,next_attempt_at DATETIME,last_error VARCHAR(1000),synced_at DATETIME,INDEX ix_accounting_queue(status,next_attempt_at),FOREIGN KEY(connection_id) REFERENCES accounting_connections(id) ON DELETE CASCADE) ENGINE=InnoDB;

-- Privacy, retention, exports, and audit
CREATE TABLE consent_records (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,purpose_code VARCHAR(80) NOT NULL,policy_version VARCHAR(40) NOT NULL,status ENUM('granted','withdrawn') NOT NULL,evidence JSON,recorded_at DATETIME NOT NULL,withdrawn_at DATETIME,FOREIGN KEY(client_id) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE data_export_requests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,client_id BIGINT UNSIGNED NOT NULL,requested_by BIGINT UNSIGNED NOT NULL,status ENUM('requested','identity_verification','processing','ready','delivered','rejected','expired') NOT NULL DEFAULT 'requested',scope JSON,storage_reference VARCHAR(500),expires_at DATETIME,completed_at DATETIME,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(client_id) REFERENCES users(id),FOREIGN KEY(requested_by) REFERENCES users(id)) ENGINE=InnoDB;
CREATE TABLE retention_policies (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,data_category VARCHAR(80) NOT NULL,retention_days INT UNSIGNED NOT NULL,legal_hold_supported BOOLEAN NOT NULL DEFAULT FALSE,active BOOLEAN NOT NULL DEFAULT TRUE,UNIQUE KEY uq_retention_category(clinic_id,data_category),FOREIGN KEY(clinic_id) REFERENCES clinics(id)) ENGINE=InnoDB;
CREATE TABLE audit_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,clinic_id BIGINT UNSIGNED NOT NULL,actor_user_id BIGINT UNSIGNED,correlation_id CHAR(36) NOT NULL,action VARCHAR(100) NOT NULL,entity_type VARCHAR(80) NOT NULL,entity_id BIGINT UNSIGNED,outcome ENUM('success','denied','failure') NOT NULL DEFAULT 'success',ip_address VARBINARY(16),user_agent VARCHAR(500),metadata JSON COMMENT 'Never store clinical note contents or credentials here',created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,INDEX ix_audit_entity(clinic_id,entity_type,entity_id,created_at),INDEX ix_audit_actor(actor_user_id,created_at),FOREIGN KEY(clinic_id) REFERENCES clinics(id),FOREIGN KEY(actor_user_id) REFERENCES users(id)) ENGINE=InnoDB;

INSERT INTO roles(code,name,description) VALUES
('super_admin','Super Admin','Platform configuration, compliance, integrations, and cross-clinic administration'),
('clinic_admin','Clinic Admin','Clinic operations, schedules, rooms, services, reporting, and billing oversight'),
('reception','Reception','Client search, bookings, rescheduling, payments, and waitlists'),
('practitioner','Practitioner','Own schedule, assigned clients, forms, notes, and related invoices'),
('accountant','Accountant','Financial records, exports, reconciliation, and accounting settings');
