CREATE TABLE user_profile_images (
 user_id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
 mime_type VARCHAR(40) NOT NULL,
 image_data MEDIUMBLOB NOT NULL,
 byte_size INT UNSIGNED NOT NULL,
 content_hash CHAR(64) NOT NULL,
 updated_by BIGINT UNSIGNED NULL,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY(updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;
