<?php
declare(strict_types=1);

namespace Wellness\Service;

use Throwable;
use Wellness\Auth\AuthContext;
use Wellness\Database;
use Wellness\Http\ApiException;

final class AdminService
{
    public function __construct(private readonly Database $database,private readonly AuditLogger $audit) {}

    public function practitioners(AuthContext $actor): array
    {
        $this->superAdmin($actor);
        $statement=$this->database->connection()->prepare("SELECT p.id AS practitioner_id,u.id AS user_id,u.display_name,u.email,u.status,p.discipline,p.credentials,p.booking_mode,p.active,MIN(pl.location_id) AS location_id,GROUP_CONCAT(l.name ORDER BY l.name SEPARATOR ', ') AS locations FROM practitioners p JOIN users u ON u.id=p.user_id LEFT JOIN practitioner_locations pl ON pl.practitioner_id=p.id AND pl.active=1 LEFT JOIN locations l ON l.id=pl.location_id WHERE u.clinic_id=:clinic GROUP BY p.id,u.id,u.display_name,u.email,u.status,p.discipline,p.credentials,p.booking_mode,p.active ORDER BY u.display_name");
        $statement->execute(['clinic'=>$actor->clinicId]);return $statement->fetchAll();
    }

    public function onboardPractitioner(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['tenant_id','object_id','email','display_name','location_id','discipline']);$this->ownedLocation($actor,(int)$body['location_id']);
        $tenantId=strtolower(trim((string)$body['tenant_id']));$objectId=strtolower(trim((string)$body['object_id']));$email=strtolower(trim((string)$body['email']));$displayName=trim((string)$body['display_name']);$discipline=trim((string)$body['discipline']);$credentials=$this->optional($body,'credentials');$bookingMode=(string)($body['booking_mode']??'practitioner_managed');
        $uuid='/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i';
        if(!preg_match($uuid,$tenantId))throw new ApiException(422,'validation_error','Enter a valid Entra tenant ID.',['tenant_id'=>'Invalid UUID']);
        if(!preg_match($uuid,$objectId))throw new ApiException(422,'validation_error','Enter a valid Entra Object ID.',['object_id'=>'Invalid UUID']);
        if(filter_var($email,FILTER_VALIDATE_EMAIL)===false||strlen($email)>190)throw new ApiException(422,'validation_error','Enter a valid email address.',['email'=>'Invalid email']);
        if(strlen($displayName)>150)throw new ApiException(422,'validation_error','The display name is too long.',['display_name'=>'Maximum 150 characters']);
        if(strlen($discipline)>100)throw new ApiException(422,'validation_error','The discipline is too long.',['discipline'=>'Maximum 100 characters']);
        if($credentials!==null&&strlen($credentials)>500)throw new ApiException(422,'validation_error','The credentials are too long.',['credentials'=>'Maximum 500 characters']);
        if(!in_array($bookingMode,['practitioner_managed','clinic_managed'],true))throw new ApiException(422,'validation_error','Invalid booking mode.',['booking_mode'=>'Invalid booking mode']);
        $pdo=$this->database->connection();
        $existing=$pdo->prepare("SELECT 1 FROM identity_links WHERE provider='microsoft' AND tenant_id=:tenant AND provider_subject=:subject");$existing->execute(['tenant'=>$tenantId,'subject'=>$objectId]);if($existing->fetchColumn())throw new ApiException(409,'identity_already_linked','This Entra identity is already linked to a local user.');
        $existing=$pdo->prepare('SELECT 1 FROM users WHERE clinic_id=:clinic AND email=:email');$existing->execute(['clinic'=>$actor->clinicId,'email'=>$email]);if($existing->fetchColumn())throw new ApiException(409,'email_already_exists','A user with this email already exists in the clinic.');
        try{$pdo->beginTransaction();
            $statement=$pdo->prepare("INSERT INTO users(clinic_id,email,display_name,user_type,status) VALUES(:clinic,:email,:name,'staff','active')");$statement->execute(['clinic'=>$actor->clinicId,'email'=>$email,'name'=>$displayName]);$userId=(int)$pdo->lastInsertId();
            $statement=$pdo->prepare("INSERT INTO identity_links(user_id,provider,tenant_id,provider_subject,email_at_link_time) VALUES(:user,'microsoft',:tenant,:subject,:email)");$statement->execute(['user'=>$userId,'tenant'=>$tenantId,'subject'=>$objectId,'email'=>$email]);
            $statement=$pdo->prepare("INSERT INTO user_roles(user_id,role_id,location_id,assigned_by) SELECT :user,id,:location,:actor FROM roles WHERE code='practitioner'");$statement->execute(['user'=>$userId,'location'=>(int)$body['location_id'],'actor'=>$actor->userId]);if($statement->rowCount()!==1)throw new ApiException(500,'role_not_configured','The practitioner role is not configured.');
            $statement=$pdo->prepare('INSERT INTO staff_accounts(user_id,mfa_required) VALUES(:user,1)');$statement->execute(['user'=>$userId]);
            $statement=$pdo->prepare('INSERT INTO practitioners(user_id,discipline,credentials,booking_mode) VALUES(:user,:discipline,:credentials,:mode)');$statement->execute(['user'=>$userId,'discipline'=>$discipline,'credentials'=>$credentials,'mode'=>$bookingMode]);$practitionerId=(int)$pdo->lastInsertId();
            $statement=$pdo->prepare('INSERT INTO practitioner_locations(practitioner_id,location_id,active) VALUES(:practitioner,:location,1)');$statement->execute(['practitioner'=>$practitionerId,'location'=>(int)$body['location_id']]);
            $this->audit->write($actor->clinicId,$actor,$correlationId,'practitioner.onboard','practitioner',$practitionerId,'success',['user_id'=>$userId,'location_id'=>(int)$body['location_id']]);$pdo->commit();return ['id'=>$practitionerId,'user_id'=>$userId,'status'=>'active'];
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function updatePractitioner(AuthContext $actor,int $practitionerId,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['display_name','email','location_id','discipline','booking_mode','status']);$this->ownedLocation($actor,(int)$body['location_id']);
        $displayName=trim((string)$body['display_name']);$email=strtolower(trim((string)$body['email']));$discipline=trim((string)$body['discipline']);$credentials=$this->optional($body,'credentials');$bookingMode=(string)$body['booking_mode'];$status=(string)$body['status'];$active=(bool)($body['active']??true);
        if($displayName===''||strlen($displayName)>150)throw new ApiException(422,'validation_error','Enter a valid display name.',['display_name'=>'Required; maximum 150 characters']);
        if(filter_var($email,FILTER_VALIDATE_EMAIL)===false||strlen($email)>190)throw new ApiException(422,'validation_error','Enter a valid email address.',['email'=>'Invalid email']);
        if($discipline===''||strlen($discipline)>100)throw new ApiException(422,'validation_error','Enter a valid discipline.',['discipline'=>'Required; maximum 100 characters']);
        if($credentials!==null&&strlen($credentials)>500)throw new ApiException(422,'validation_error','The credentials are too long.',['credentials'=>'Maximum 500 characters']);
        if(!in_array($bookingMode,['practitioner_managed','clinic_managed'],true))throw new ApiException(422,'validation_error','Invalid booking mode.',['booking_mode'=>'Invalid booking mode']);
        if(!in_array($status,['active','inactive'],true))throw new ApiException(422,'validation_error','Invalid account status.',['status'=>'Invalid status']);
        $pdo=$this->database->connection();
        try{$pdo->beginTransaction();
            $find=$pdo->prepare('SELECT p.user_id FROM practitioners p JOIN users u ON u.id=p.user_id WHERE p.id=:practitioner AND u.clinic_id=:clinic FOR UPDATE');$find->execute(['practitioner'=>$practitionerId,'clinic'=>$actor->clinicId]);$userId=$find->fetchColumn();if(!$userId)throw new ApiException(404,'practitioner_not_found','Practitioner not found.');
            $duplicate=$pdo->prepare('SELECT 1 FROM users WHERE clinic_id=:clinic AND email=:email AND id<>:user');$duplicate->execute(['clinic'=>$actor->clinicId,'email'=>$email,'user'=>(int)$userId]);if($duplicate->fetchColumn())throw new ApiException(409,'email_already_exists','A user with this email already exists in the clinic.');
            $statement=$pdo->prepare('UPDATE users SET display_name=:name,email=:email,status=:status WHERE id=:user');$statement->execute(['name'=>$displayName,'email'=>$email,'status'=>$status,'user'=>(int)$userId]);
            $statement=$pdo->prepare('UPDATE practitioners SET discipline=:discipline,credentials=:credentials,booking_mode=:mode,active=:active WHERE id=:practitioner');$statement->execute(['discipline'=>$discipline,'credentials'=>$credentials,'mode'=>$bookingMode,'active'=>$active?1:0,'practitioner'=>$practitionerId]);
            $statement=$pdo->prepare('UPDATE practitioner_locations SET active=0 WHERE practitioner_id=:practitioner');$statement->execute(['practitioner'=>$practitionerId]);
            $statement=$pdo->prepare('INSERT INTO practitioner_locations(practitioner_id,location_id,active) VALUES(:practitioner,:location,1) ON DUPLICATE KEY UPDATE active=1');$statement->execute(['practitioner'=>$practitionerId,'location'=>(int)$body['location_id']]);
            $this->audit->write($actor->clinicId,$actor,$correlationId,'practitioner.update','practitioner',$practitionerId,'success',['user_id'=>(int)$userId,'location_id'=>(int)$body['location_id']]);$pdo->commit();return ['id'=>$practitionerId,'status'=>$status,'active'=>$active];
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function updateClinic(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['name']);
        $name=trim((string)$body['name']);$legalName=$this->optional($body,'legal_name');$email=$this->optional($body,'email');$phone=$this->optional($body,'phone');
        if(strlen($name)>160)throw new ApiException(422,'validation_error','The operating name is too long.',['name'=>'Maximum 160 characters']);
        if($legalName!==null&&strlen($legalName)>190)throw new ApiException(422,'validation_error','The legal name is too long.',['legal_name'=>'Maximum 190 characters']);
        if($email!==null&&(strlen($email)>190||filter_var($email,FILTER_VALIDATE_EMAIL)===false))throw new ApiException(422,'validation_error','Enter a valid email address.',['email'=>'Invalid email']);
        if($phone!==null&&strlen($phone)>40)throw new ApiException(422,'validation_error','The phone number is too long.',['phone'=>'Maximum 40 characters']);
        $pdo=$this->database->connection();
        try{$pdo->beginTransaction();$statement=$pdo->prepare('UPDATE clinics SET name=:name,legal_name=:legal_name,email=:email,phone=:phone WHERE id=:clinic');$statement->execute(['name'=>$name,'legal_name'=>$legalName,'email'=>$email,'phone'=>$phone,'clinic'=>$actor->clinicId]);if($statement->rowCount()===0){$check=$pdo->prepare('SELECT 1 FROM clinics WHERE id=:clinic');$check->execute(['clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'clinic_not_found','Clinic not found.');}$this->audit->write($actor->clinicId,$actor,$correlationId,'clinic.settings.update','clinic',$actor->clinicId,'success',['fields'=>['name','legal_name','email','phone']]);$pdo->commit();return $this->clinic($actor->clinicId);}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    public function catalogueSettings(AuthContext $actor): array{$this->superAdmin($actor);$pdo=$this->database->connection();$c=$pdo->prepare('SELECT id,name,description FROM service_categories WHERE clinic_id=:clinic ORDER BY name');$c->execute(['clinic'=>$actor->clinicId]);$t=$pdo->prepare('SELECT id,code,name,rate_basis_points,active FROM taxes WHERE clinic_id=:clinic ORDER BY name');$t->execute(['clinic'=>$actor->clinicId]);$s=$pdo->prepare('SELECT default_lead_time_minutes,default_booking_horizon_days,default_cancellation_window_minutes,slot_increment_minutes,currency FROM clinic_booking_settings WHERE clinic_id=:clinic');$s->execute(['clinic'=>$actor->clinicId]);return ['categories'=>$c->fetchAll(),'taxes'=>$t->fetchAll(),'settings'=>$s->fetch()?:null];}
    public function createServiceCategory(AuthContext $actor,array $body,string $cid): array{$this->superAdmin($actor);$this->required($body,['name']);$name=trim((string)$body['name']);if(strlen($name)>120)throw new ApiException(422,'validation_error','Category name is too long.');$s=$this->database->connection()->prepare('INSERT INTO service_categories(clinic_id,name,description) VALUES(:clinic,:name,:description)');$s->execute(['clinic'=>$actor->clinicId,'name'=>$name,'description'=>$this->optional($body,'description')]);return $this->created($actor,$cid,'service_category',(int)$this->database->connection()->lastInsertId());}
    public function createTax(AuthContext $actor,array $body,string $cid): array{$this->superAdmin($actor);$this->required($body,['code','name','rate_basis_points']);$rate=(int)$body['rate_basis_points'];if($rate<0||$rate>10000)throw new ApiException(422,'validation_error','Tax rate must be between 0 and 100%.');$s=$this->database->connection()->prepare('INSERT INTO taxes(clinic_id,code,name,rate_basis_points) VALUES(:clinic,:code,:name,:rate)');$s->execute(['clinic'=>$actor->clinicId,'code'=>strtoupper(trim((string)$body['code'])),'name'=>trim((string)$body['name']),'rate'=>$rate]);return $this->created($actor,$cid,'tax',(int)$this->database->connection()->lastInsertId());}
    public function updateBookingSettings(AuthContext $actor,array $body,string $cid): array{$this->superAdmin($actor);$this->required($body,['default_lead_time_minutes','default_booking_horizon_days','default_cancellation_window_minutes']);$s=$this->database->connection()->prepare("INSERT INTO clinic_booking_settings(clinic_id,default_lead_time_minutes,default_booking_horizon_days,default_cancellation_window_minutes,slot_increment_minutes,currency) VALUES(:clinic,:lead,:horizon,:cancel,15,'CAD') ON DUPLICATE KEY UPDATE default_lead_time_minutes=VALUES(default_lead_time_minutes),default_booking_horizon_days=VALUES(default_booking_horizon_days),default_cancellation_window_minutes=VALUES(default_cancellation_window_minutes)");$s->execute(['clinic'=>$actor->clinicId,'lead'=>(int)$body['default_lead_time_minutes'],'horizon'=>(int)$body['default_booking_horizon_days'],'cancel'=>(int)$body['default_cancellation_window_minutes']]);$this->audit->write($actor->clinicId,$actor,$cid,'booking.settings.update','clinic',$actor->clinicId);return ['updated'=>true];}

    public function createLocation(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['name','timezone']);$this->validateLocation($body);
        $sql='INSERT INTO locations(clinic_id,name,timezone,address_line1,address_line2,city,province,postal_code,phone) VALUES(:clinic,:name,:timezone,:line1,:line2,:city,:province,:postal,:phone)';
        $statement=$this->database->connection()->prepare($sql);$statement->execute(['clinic'=>$actor->clinicId,'name'=>trim((string)$body['name']),'timezone'=>$body['timezone'],'line1'=>$this->optional($body,'address_line1'),'line2'=>$this->optional($body,'address_line2'),'city'=>$this->optional($body,'city'),'province'=>$this->optional($body,'province'),'postal'=>$this->optional($body,'postal_code'),'phone'=>$this->optional($body,'phone')]);
        return $this->created($actor,$correlationId,'location',(int)$this->database->connection()->lastInsertId());
    }

    public function locations(AuthContext $actor): array
    {
        $this->superAdmin($actor);$statement=$this->database->connection()->prepare('SELECT id,name,timezone,address_line1,address_line2,city,province,postal_code,phone,is_bookable FROM locations WHERE clinic_id=:clinic ORDER BY name');$statement->execute(['clinic'=>$actor->clinicId]);return $statement->fetchAll();
    }

    public function updateLocation(AuthContext $actor,int $locationId,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['name','timezone']);$this->validateLocation($body);
        $statement=$this->database->connection()->prepare('UPDATE locations SET name=:name,timezone=:timezone,address_line1=:line1,address_line2=:line2,city=:city,province=:province,postal_code=:postal,phone=:phone,is_bookable=:bookable WHERE id=:id AND clinic_id=:clinic');
        $statement->execute(['name'=>trim((string)$body['name']),'timezone'=>$body['timezone'],'line1'=>$this->optional($body,'address_line1'),'line2'=>$this->optional($body,'address_line2'),'city'=>$this->optional($body,'city'),'province'=>$this->optional($body,'province'),'postal'=>$this->optional($body,'postal_code'),'phone'=>$this->optional($body,'phone'),'bookable'=>(bool)($body['is_bookable']??true)?1:0,'id'=>$locationId,'clinic'=>$actor->clinicId]);
        if($statement->rowCount()===0){$check=$this->database->connection()->prepare('SELECT 1 FROM locations WHERE id=:id AND clinic_id=:clinic');$check->execute(['id'=>$locationId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'location_not_found','Location not found.');}
        $this->audit->write($actor->clinicId,$actor,$correlationId,'location.update','location',$locationId);return ['id'=>$locationId];
    }

    public function createRoom(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$this->required($body,['location_id','name']);$this->ownedLocation($actor,(int)$body['location_id']);$this->validateRoom($body);
        $statement=$this->database->connection()->prepare('INSERT INTO rooms(location_id,name,room_type,equipment_notes,turnover_minutes,is_bookable) VALUES(:location,:name,:type,:notes,:turnover,:bookable)');$statement->execute(['location'=>(int)$body['location_id'],'name'=>trim((string)$body['name']),'type'=>$this->optional($body,'room_type'),'notes'=>$this->optional($body,'equipment_notes'),'turnover'=>(int)($body['turnover_minutes']??0),'bookable'=>(bool)($body['is_bookable']??true)?1:0]);
        return $this->created($actor,$correlationId,'room',(int)$this->database->connection()->lastInsertId());
    }

    public function rooms(AuthContext $actor): array{$this->superAdmin($actor);$statement=$this->database->connection()->prepare('SELECT r.id,r.location_id,r.name,r.room_type,r.equipment_notes,r.turnover_minutes,r.is_bookable,l.name AS location_name FROM rooms r JOIN locations l ON l.id=r.location_id WHERE l.clinic_id=:clinic ORDER BY l.name,r.name');$statement->execute(['clinic'=>$actor->clinicId]);return $statement->fetchAll();}
    public function updateRoom(AuthContext $actor,int $roomId,array $body,string $correlationId): array{$this->superAdmin($actor);$this->required($body,['location_id','name']);$this->ownedLocation($actor,(int)$body['location_id']);$this->validateRoom($body);$statement=$this->database->connection()->prepare('UPDATE rooms r JOIN locations current_location ON current_location.id=r.location_id SET r.location_id=:location,r.name=:name,r.room_type=:type,r.equipment_notes=:notes,r.turnover_minutes=:turnover,r.is_bookable=:bookable WHERE r.id=:id AND current_location.clinic_id=:clinic');$statement->execute(['location'=>(int)$body['location_id'],'name'=>trim((string)$body['name']),'type'=>$this->optional($body,'room_type'),'notes'=>$this->optional($body,'equipment_notes'),'turnover'=>(int)($body['turnover_minutes']??0),'bookable'=>(bool)($body['is_bookable']??true)?1:0,'id'=>$roomId,'clinic'=>$actor->clinicId]);if($statement->rowCount()===0){$check=$this->database->connection()->prepare('SELECT 1 FROM rooms r JOIN locations l ON l.id=r.location_id WHERE r.id=:id AND l.clinic_id=:clinic');$check->execute(['id'=>$roomId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'room_not_found','Room not found.');}$this->audit->write($actor->clinicId,$actor,$correlationId,'room.update','room',$roomId);return ['id'=>$roomId];}
    public function roomCapabilities(AuthContext $actor): array{$this->superAdmin($actor);$pdo=$this->database->connection();$c=$pdo->prepare('SELECT id,code,name FROM room_capabilities WHERE clinic_id=:clinic ORDER BY name');$c->execute(['clinic'=>$actor->clinicId]);$r=$pdo->prepare('SELECT a.room_id,a.capability_id FROM room_capability_assignments a JOIN rooms r ON r.id=a.room_id JOIN locations l ON l.id=r.location_id WHERE l.clinic_id=:clinic');$r->execute(['clinic'=>$actor->clinicId]);$s=$pdo->prepare('SELECT a.service_id,a.capability_id FROM service_room_capability_requirements a JOIN services s ON s.id=a.service_id WHERE s.clinic_id=:clinic');$s->execute(['clinic'=>$actor->clinicId]);return ['capabilities'=>$c->fetchAll(),'rooms'=>$r->fetchAll(),'services'=>$s->fetchAll()];}
    public function createRoomCapability(AuthContext $actor,array $body,string $correlationId): array{$this->superAdmin($actor);$this->required($body,['name']);$name=trim((string)$body['name']);if(strlen($name)>120)throw new ApiException(422,'validation_error','Capability name is too long.');$code=strtolower(trim((string)preg_replace('/[^a-z0-9]+/i','_',$name),'_'));if($code==='')throw new ApiException(422,'validation_error','Enter a valid capability name.');$s=$this->database->connection()->prepare('INSERT INTO room_capabilities(clinic_id,code,name) VALUES(:clinic,:code,:name)');$s->execute(['clinic'=>$actor->clinicId,'code'=>$code,'name'=>$name]);return $this->created($actor,$correlationId,'room_capability',(int)$this->database->connection()->lastInsertId());}
    public function updateRoomCapabilityAssignments(AuthContext $actor,array $body,string $correlationId): array{$this->superAdmin($actor);$roomId=(int)($body['room_id']??0);$serviceId=(int)($body['service_id']??0);$roomIds=array_unique(array_map('intval',$body['room_capability_ids']??[]));$serviceIds=array_unique(array_map('intval',$body['service_capability_ids']??[]));$pdo=$this->database->connection();try{$pdo->beginTransaction();if($roomId){$check=$pdo->prepare('SELECT 1 FROM rooms r JOIN locations l ON l.id=r.location_id WHERE r.id=:id AND l.clinic_id=:clinic');$check->execute(['id'=>$roomId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'room_not_found','Room not found.');$pdo->prepare('DELETE FROM room_capability_assignments WHERE room_id=:id')->execute(['id'=>$roomId]);$i=$pdo->prepare('INSERT INTO room_capability_assignments(room_id,capability_id) SELECT :room,id FROM room_capabilities WHERE id=:capability AND clinic_id=:clinic');foreach($roomIds as $cap)$i->execute(['room'=>$roomId,'capability'=>$cap,'clinic'=>$actor->clinicId]);}if($serviceId){$check=$pdo->prepare('SELECT 1 FROM services WHERE id=:id AND clinic_id=:clinic');$check->execute(['id'=>$serviceId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'service_not_found','Service not found.');$pdo->prepare('DELETE FROM service_room_capability_requirements WHERE service_id=:id')->execute(['id'=>$serviceId]);$i=$pdo->prepare('INSERT INTO service_room_capability_requirements(service_id,capability_id) SELECT :service,id FROM room_capabilities WHERE id=:capability AND clinic_id=:clinic');foreach($serviceIds as $cap)$i->execute(['service'=>$serviceId,'capability'=>$cap,'clinic'=>$actor->clinicId]);}$this->audit->write($actor->clinicId,$actor,$correlationId,'room.capabilities.update','clinic',$actor->clinicId);$pdo->commit();return ['updated'=>true];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
    public function roomPractitionerRestrictions(AuthContext $actor): array{$this->superAdmin($actor);$s=$this->database->connection()->prepare('SELECT x.room_id,x.practitioner_id,x.allowed FROM room_practitioner_restrictions x JOIN rooms r ON r.id=x.room_id JOIN locations l ON l.id=r.location_id WHERE l.clinic_id=:clinic');$s->execute(['clinic'=>$actor->clinicId]);return $s->fetchAll();}
    public function updateRoomPractitioners(AuthContext $actor,int $roomId,array $body,string $cid): array{$this->superAdmin($actor);$ids=array_unique(array_map('intval',$body['practitioner_ids']??[]));$pdo=$this->database->connection();try{$pdo->beginTransaction();$check=$pdo->prepare('SELECT 1 FROM rooms r JOIN locations l ON l.id=r.location_id WHERE r.id=:id AND l.clinic_id=:clinic');$check->execute(['id'=>$roomId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'room_not_found','Room not found.');$pdo->prepare('DELETE FROM room_practitioner_restrictions WHERE room_id=:id')->execute(['id'=>$roomId]);$i=$pdo->prepare('INSERT INTO room_practitioner_restrictions(room_id,practitioner_id,allowed) SELECT :room,p.id,1 FROM practitioners p JOIN users u ON u.id=p.user_id WHERE p.id=:practitioner AND u.clinic_id=:clinic');foreach($ids as $id)$i->execute(['room'=>$roomId,'practitioner'=>$id,'clinic'=>$actor->clinicId]);$this->audit->write($actor->clinicId,$actor,$cid,'room.practitioners.update','room',$roomId);$pdo->commit();return ['updated'=>true];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}

    public function createStaff(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->admin($actor);$this->required($body,['tenant_id','object_id','email','display_name','role']);
        $allowed=['super_admin','clinic_admin','reception','practitioner','accountant'];if(!in_array($body['role'],$allowed,true))throw new ApiException(422,'validation_error','Invalid staff role.',['role'=>'Invalid role']);
        $pdo=$this->database->connection();
        try{$pdo->beginTransaction();$statement=$pdo->prepare("INSERT INTO users(clinic_id,email,display_name,user_type,status) VALUES(:clinic,:email,:name,'staff','active')");$statement->execute(['clinic'=>$actor->clinicId,'email'=>strtolower(trim($body['email'])),'name'=>$body['display_name']]);$id=(int)$pdo->lastInsertId();
            $statement=$pdo->prepare("INSERT INTO identity_links(user_id,provider,tenant_id,provider_subject,email_at_link_time) VALUES(:user,'microsoft',:tenant,:subject,:email)");$statement->execute(['user'=>$id,'tenant'=>$body['tenant_id'],'subject'=>$body['object_id'],'email'=>strtolower(trim($body['email']))]);
            $statement=$pdo->prepare('INSERT INTO user_roles(user_id,role_id,location_id,assigned_by) SELECT :user,id,:location,:actor FROM roles WHERE code=:role');$statement->execute(['user'=>$id,'location'=>isset($body['location_id'])?(int)$body['location_id']:null,'actor'=>$actor->userId,'role'=>$body['role']]);
            $statement=$pdo->prepare('INSERT INTO staff_accounts(user_id,mfa_required) VALUES(:user,1)');$statement->execute(['user'=>$id]);$this->audit->write($actor->clinicId,$actor,$correlationId,'staff.create','user',$id,'success',['role'=>$body['role']]);$pdo->commit();return ['id'=>$id,'status'=>'active'];
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    public function staff(AuthContext $actor): array
    {
        $this->superAdmin($actor);
        $s=$this->database->connection()->prepare("SELECT u.id,u.display_name,u.email,u.status,GROUP_CONCAT(DISTINCT r.code ORDER BY r.code) roles,GROUP_CONCAT(DISTINCT permission.code ORDER BY permission.code) permissions FROM users u JOIN staff_accounts a ON a.user_id=u.id LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id LEFT JOIN user_permissions user_permission ON user_permission.user_id=u.id LEFT JOIN permissions permission ON permission.id=user_permission.permission_id WHERE u.clinic_id=:clinic GROUP BY u.id,u.display_name,u.email,u.status ORDER BY u.display_name");
        $s->execute(['clinic'=>$actor->clinicId]);$rows=$s->fetchAll();
        foreach($rows as &$row){$row['roles']=$row['roles']?explode(',',$row['roles']):[];$row['permissions']=$row['permissions']?explode(',',$row['permissions']):[];}
        return $rows;
    }

    public function updateStaff(AuthContext $actor,int $userId,array $body,string $cid): array
    {
        $this->superAdmin($actor);$this->required($body,['display_name','email','status','roles']);
        if($userId===$actor->userId)throw new ApiException(422,'self_role_change','Use another Super Admin to change your own access.');
        $roles=array_values(array_unique($body['roles']));$allowed=['super_admin','clinic_admin','reception','practitioner','accountant'];foreach($roles as $role)if(!in_array($role,$allowed,true))throw new ApiException(422,'validation_error','Invalid role.');
        $permissions=array_values(array_unique($body['permissions']??[]));$allowedPermissions=['schedule_for_other_practitioners'];foreach($permissions as $permission)if(!in_array($permission,$allowedPermissions,true))throw new ApiException(422,'validation_error','Invalid permission.');
        if($permissions!==[]&&!in_array('practitioner',$roles,true))throw new ApiException(422,'validation_error','Cross-practitioner scheduling can only be assigned to a practitioner.');
        if(!in_array($body['status'],['active','inactive','locked'],true))throw new ApiException(422,'validation_error','Invalid staff status.');
        $pdo=$this->database->connection();
        try{
            $pdo->beginTransaction();$s=$pdo->prepare("UPDATE users SET display_name=:name,email=:email,status=:status WHERE id=:id AND clinic_id=:clinic AND user_type='staff'");$s->execute(['name'=>trim((string)$body['display_name']),'email'=>strtolower(trim((string)$body['email'])),'status'=>$body['status'],'id'=>$userId,'clinic'=>$actor->clinicId]);
            $check=$pdo->prepare('SELECT 1 FROM users WHERE id=:id AND clinic_id=:clinic');$check->execute(['id'=>$userId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'staff_not_found','Staff member not found.');
            $pdo->prepare('DELETE FROM user_roles WHERE user_id=:id')->execute(['id'=>$userId]);$insert=$pdo->prepare('INSERT INTO user_roles(user_id,role_id,assigned_by) SELECT :user,id,:actor FROM roles WHERE code=:role');foreach($roles as $role)$insert->execute(['user'=>$userId,'actor'=>$actor->userId,'role'=>$role]);
            $pdo->prepare('DELETE FROM user_permissions WHERE user_id=:id')->execute(['id'=>$userId]);$insertPermission=$pdo->prepare('INSERT INTO user_permissions(user_id,permission_id,assigned_by) SELECT :user,id,:actor FROM permissions WHERE code=:permission');foreach($permissions as $permission)$insertPermission->execute(['user'=>$userId,'actor'=>$actor->userId,'permission'=>$permission]);
            $this->audit->write($actor->clinicId,$actor,$cid,'staff.update','user',$userId,'success',['roles'=>$roles,'permissions'=>$permissions,'status'=>$body['status']]);$pdo->commit();return ['id'=>$userId];
        }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function teamProfiles(AuthContext $actor): array
    {
        $this->superAdmin($actor);
        $statement = $this->database->connection()->prepare(
            "SELECT u.id AS user_id,u.display_name,u.status,p.id AS practitioner_id,
                    t.slug,t.section,t.public_title,t.public_title_fr,t.summary,t.summary_fr,t.display_order,t.published,t.show_booking_action,
                    CASE WHEN i.user_id IS NULL THEN 0 ELSE 1 END has_image
               FROM users u
               JOIN staff_accounts a ON a.user_id=u.id
          LEFT JOIN practitioners p ON p.user_id=u.id
          LEFT JOIN public_team_profiles t ON t.user_id=u.id
          LEFT JOIN user_profile_images i ON i.user_id=u.id
              WHERE u.clinic_id=:clinic
              ORDER BY CASE WHEN p.id IS NULL THEN 1 ELSE 0 END,u.display_name"
        );
        $statement->execute(['clinic' => $actor->clinicId]);
        return $statement->fetchAll();
    }

    public function updateTeamProfile(AuthContext $actor, int $userId, array $body, string $correlationId): array
    {
        $this->superAdmin($actor);
        $this->required($body, ['slug','section','public_title']);
        $slug = strtolower(trim((string)$body['slug']));
        $section = (string)$body['section'];
        $title = trim((string)$body['public_title']);
        $titleFr = $this->optional($body, 'public_title_fr');
        $summary = $this->optional($body, 'summary');
        $summaryFr = $this->optional($body, 'summary_fr');
        $order = (int)($body['display_order'] ?? 100);
        $published = (bool)($body['published'] ?? false);
        $showBooking = (bool)($body['show_booking_action'] ?? false);
        if (preg_match('/^[a-z0-9](?:[a-z0-9-]{0,98}[a-z0-9])?$/', $slug) !== 1) throw new ApiException(422,'validation_error','Use a lowercase URL name containing letters, numbers, and hyphens.',['slug'=>'Invalid URL name']);
        if (!in_array($section,['practitioner','administration'],true)) throw new ApiException(422,'validation_error','Choose a valid team section.',['section'=>'Invalid section']);
        if ($title==='' || strlen($title)>150 || ($titleFr!==null && strlen($titleFr)>150)) throw new ApiException(422,'validation_error','Team titles may contain up to 150 characters.',['public_title'=>'Required; maximum 150 characters']);
        if (($summary!==null && strlen($summary)>1000) || ($summaryFr!==null && strlen($summaryFr)>1000)) throw new ApiException(422,'validation_error','Team summaries may contain up to 1000 characters.',['summary'=>'Maximum 1000 characters']);
        if ($order<0 || $order>65535) throw new ApiException(422,'validation_error','Display order must be between 0 and 65535.',['display_order'=>'Invalid display order']);
        $pdo = $this->database->connection();
        $check = $pdo->prepare("SELECT p.id practitioner_id FROM users u JOIN staff_accounts a ON a.user_id=u.id LEFT JOIN practitioners p ON p.user_id=u.id AND p.active=1 WHERE u.id=:user AND u.clinic_id=:clinic AND u.user_type='staff'");
        $check->execute(['user'=>$userId,'clinic'=>$actor->clinicId]);
        $staff = $check->fetch();
        if (!$staff) throw new ApiException(404,'staff_not_found','Staff member not found.');
        if ($section==='practitioner' && !$staff['practitioner_id']) throw new ApiException(422,'validation_error','Only an active practitioner can appear in the practitioner section.',['section'=>'Active practitioner required']);
        if ($showBooking && ($section!=='practitioner' || !$staff['practitioner_id'])) throw new ApiException(422,'validation_error','Booking can only be shown for an active practitioner.',['show_booking_action'=>'Active practitioner required']);
        $statement = $pdo->prepare("INSERT INTO public_team_profiles(user_id,clinic_id,slug,section,public_title,public_title_fr,summary,summary_fr,display_order,published,show_booking_action,updated_by)
            VALUES(:user,:clinic,:slug,:section,:title,:title_fr,:summary,:summary_fr,:display_order,:published,:booking,:actor)
            ON DUPLICATE KEY UPDATE slug=VALUES(slug),section=VALUES(section),public_title=VALUES(public_title),public_title_fr=VALUES(public_title_fr),summary=VALUES(summary),summary_fr=VALUES(summary_fr),display_order=VALUES(display_order),published=VALUES(published),show_booking_action=VALUES(show_booking_action),updated_by=VALUES(updated_by)");
        try {
            $statement->execute(['user'=>$userId,'clinic'=>$actor->clinicId,'slug'=>$slug,'section'=>$section,'title'=>$title,'title_fr'=>$titleFr,'summary'=>$summary,'summary_fr'=>$summaryFr,'display_order'=>$order,'published'=>$published?1:0,'booking'=>$showBooking?1:0,'actor'=>$actor->userId]);
        } catch (\PDOException $e) {
            if ((string)$e->getCode()==='23000') throw new ApiException(409,'slug_already_exists','That public profile URL is already in use.',['slug'=>'Already in use']);
            throw $e;
        }
        $this->audit->write($actor->clinicId,$actor,$correlationId,'team_profile.update','user',$userId,'success',['published'=>$published,'section'=>$section]);
        return ['user_id'=>$userId,'published'=>$published];
    }

    public function createPractitioner(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->admin($actor);$this->required($body,['user_id','discipline','location_id']);$this->ownedLocation($actor,(int)$body['location_id']);$pdo=$this->database->connection();
        try{$pdo->beginTransaction();$statement=$pdo->prepare('INSERT INTO practitioners(user_id,discipline,biography,credentials,booking_mode) SELECT id,:discipline,:bio,:credentials,:mode FROM users WHERE id=:user AND clinic_id=:clinic AND user_type=\'staff\'');$statement->execute(['discipline'=>$body['discipline'],'bio'=>$body['biography']??null,'credentials'=>$body['credentials']??null,'mode'=>$body['booking_mode']??'clinic_managed','user'=>(int)$body['user_id'],'clinic'=>$actor->clinicId]);if($statement->rowCount()!==1)throw new ApiException(422,'invalid_user','Practitioner user was not found in this clinic.');$id=(int)$pdo->lastInsertId();$statement=$pdo->prepare('INSERT INTO practitioner_locations(practitioner_id,location_id) VALUES(:p,:l)');$statement->execute(['p'=>$id,'l'=>(int)$body['location_id']]);$this->audit->write($actor->clinicId,$actor,$correlationId,'practitioner.create','practitioner',$id);$pdo->commit();return ['id'=>$id,'status'=>'active'];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function createService(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->superAdmin($actor);$options=self::durationOptions($body);$this->validateService($body,$options);$categoryId=$this->ownedServiceCategory($actor,$body['category_id']??null);$pdo=$this->database->connection();
        try{$pdo->beginTransaction();$statement=$pdo->prepare("INSERT INTO services(clinic_id,category_id,name,description,preparation_instructions,price_cents,duration_mode,lead_time_minutes,booking_horizon_days,cancellation_window_minutes,cancellation_fee_type,cancellation_fee_value,buffer_before_minutes,buffer_after_minutes,requires_room,recurrence_allowed) VALUES(:clinic,:category,:name,:description,:instructions,:price,:mode,:lead,:horizon,:cancel_window,:fee_type,:fee_value,:before,:after,:room,:recurrence)");$statement->execute(['clinic'=>$actor->clinicId,'category'=>$categoryId,'name'=>trim((string)$body['name']),'description'=>$this->optional($body,'description'),'instructions'=>$this->optional($body,'preparation_instructions'),'price'=>min(array_column($options,'price_cents')),'mode'=>count($options)>1?'selectable':'fixed','lead'=>(int)($body['lead_time_minutes']??0),'horizon'=>(int)($body['booking_horizon_days']??365),'cancel_window'=>(int)($body['cancellation_window_minutes']??1440),'fee_type'=>$body['cancellation_fee_type']??'none','fee_value'=>(int)($body['cancellation_fee_value']??0),'before'=>(int)($body['buffer_before_minutes']??0),'after'=>(int)($body['buffer_after_minutes']??0),'room'=>(bool)($body['requires_room']??true)?1:0,'recurrence'=>(bool)($body['recurrence_allowed']??false)?1:0]);$id=(int)$pdo->lastInsertId();$durationInsert=$pdo->prepare('INSERT INTO service_duration_options(service_id,duration_minutes,price_cents) VALUES(:service,:minutes,:price)');foreach($options as $option)$durationInsert->execute(['service'=>$id,'minutes'=>$option['minutes'],'price'=>$option['price_cents']]);foreach($body['practitioner_ids']??[] as $practitioner){$link=$pdo->prepare('INSERT INTO practitioner_services(practitioner_id,service_id) SELECT id,:service FROM practitioners WHERE id=:practitioner AND user_id IN(SELECT id FROM users WHERE clinic_id=:clinic)');$link->execute(['service'=>$id,'practitioner'=>(int)$practitioner,'clinic'=>$actor->clinicId]);}$this->audit->write($actor->clinicId,$actor,$correlationId,'service.create','service',$id,'success',['category_id'=>$categoryId]);$pdo->commit();return ['id'=>$id,'status'=>'active'];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }

    public function services(AuthContext $actor): array{$this->superAdmin($actor);$s=$this->database->connection()->prepare('SELECT s.id,s.category_id,c.name category_name,s.name,s.description,s.preparation_instructions,s.price_cents,s.lead_time_minutes,s.booking_horizon_days,s.buffer_before_minutes,s.buffer_after_minutes,s.requires_room,s.recurrence_allowed,s.active,d.duration_minutes,COALESCE(d.price_cents,s.price_cents) duration_price_cents FROM services s LEFT JOIN service_categories c ON c.id=s.category_id AND c.clinic_id=s.clinic_id JOIN service_duration_options d ON d.service_id=s.id AND d.active=1 WHERE s.clinic_id=:clinic ORDER BY c.name IS NULL,c.name,s.name,d.duration_minutes');$s->execute(['clinic'=>$actor->clinicId]);$result=[];foreach($s->fetchAll() as $row){$id=(int)$row['id'];$option=['minutes'=>(int)$row['duration_minutes'],'price_cents'=>(int)$row['duration_price_cents']];if(!isset($result[$id])){$row['category_id']=$row['category_id']===null?null:(int)$row['category_id'];$row['duration_options']=[];$row['durations']=[];unset($row['duration_minutes'],$row['duration_price_cents']);$result[$id]=$row;}$result[$id]['duration_options'][]=$option;$result[$id]['durations'][]=$option['minutes'];}return array_values($result);}
    public function updateService(AuthContext $actor,int $id,array $body,string $correlationId): array{$this->superAdmin($actor);$options=self::durationOptions($body);$this->validateService($body,$options);$categoryId=$this->ownedServiceCategory($actor,$body['category_id']??null);$pdo=$this->database->connection();try{$pdo->beginTransaction();$s=$pdo->prepare('UPDATE services SET category_id=:category,name=:name,description=:description,preparation_instructions=:instructions,price_cents=:price,duration_mode=:mode,lead_time_minutes=:lead,booking_horizon_days=:horizon,buffer_before_minutes=:before,buffer_after_minutes=:after,requires_room=:room,recurrence_allowed=:recurrence,active=:active WHERE id=:id AND clinic_id=:clinic');$s->execute(['category'=>$categoryId,'name'=>trim((string)$body['name']),'description'=>$this->optional($body,'description'),'instructions'=>$this->optional($body,'preparation_instructions'),'price'=>min(array_column($options,'price_cents')),'mode'=>count($options)>1?'selectable':'fixed','lead'=>(int)($body['lead_time_minutes']??0),'horizon'=>(int)($body['booking_horizon_days']??365),'before'=>(int)($body['buffer_before_minutes']??0),'after'=>(int)($body['buffer_after_minutes']??0),'room'=>(bool)($body['requires_room']??true)?1:0,'recurrence'=>(bool)($body['recurrence_allowed']??false)?1:0,'active'=>(bool)($body['active']??true)?1:0,'id'=>$id,'clinic'=>$actor->clinicId]);$check=$pdo->prepare('SELECT 1 FROM services WHERE id=:id AND clinic_id=:clinic');$check->execute(['id'=>$id,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'service_not_found','Service not found.');$pdo->prepare('UPDATE service_duration_options SET active=0 WHERE service_id=:id')->execute(['id'=>$id]);$d=$pdo->prepare('INSERT INTO service_duration_options(service_id,duration_minutes,price_cents) VALUES(:id,:minutes,:price) ON DUPLICATE KEY UPDATE price_cents=VALUES(price_cents),active=1');foreach($options as $option)$d->execute(['id'=>$id,'minutes'=>$option['minutes'],'price'=>$option['price_cents']]);$this->audit->write($actor->clinicId,$actor,$correlationId,'service.update','service',$id,'success',['category_id'=>$categoryId]);$pdo->commit();return ['id'=>$id];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}

    public function serviceAssignments(AuthContext $actor): array{$this->superAdmin($actor);$s=$this->database->connection()->prepare('SELECT ps.practitioner_id,ps.service_id,ps.active,ps.offers_mobile,ps.offers_clinic,ps.mobile_radius_km,ps.travel_buffer_minutes,ps.mobile_fee_cents FROM practitioner_services ps JOIN services s ON s.id=ps.service_id WHERE s.clinic_id=:clinic');$s->execute(['clinic'=>$actor->clinicId]);$l=$this->database->connection()->prepare('SELECT sl.service_id,sl.location_id,sl.active FROM service_locations sl JOIN services s ON s.id=sl.service_id WHERE s.clinic_id=:clinic');$l->execute(['clinic'=>$actor->clinicId]);return ['practitioners'=>$s->fetchAll(),'locations'=>$l->fetchAll()];}
    public function updateServiceAssignments(AuthContext $actor,int $serviceId,array $body,string $correlationId): array{$this->superAdmin($actor);$practitioners=$body['practitioners']??[];$locations=$body['location_ids']??[];if(!is_array($practitioners)||!is_array($locations))throw new ApiException(422,'validation_error','Assignments must be arrays.');$pdo=$this->database->connection();try{$pdo->beginTransaction();$check=$pdo->prepare('SELECT 1 FROM services WHERE id=:id AND clinic_id=:clinic');$check->execute(['id'=>$serviceId,'clinic'=>$actor->clinicId]);if(!$check->fetchColumn())throw new ApiException(404,'service_not_found','Service not found.');$pdo->prepare('UPDATE practitioner_services SET active=0 WHERE service_id=:id')->execute(['id'=>$serviceId]);$up=$pdo->prepare('INSERT INTO practitioner_services(practitioner_id,service_id,active,offers_mobile,offers_clinic,mobile_radius_km,travel_buffer_minutes,mobile_fee_cents) SELECT p.id,:service,1,:mobile,:clinic_visit,:radius,:travel,:fee FROM practitioners p JOIN users u ON u.id=p.user_id WHERE p.id=:practitioner AND u.clinic_id=:clinic ON DUPLICATE KEY UPDATE active=1,offers_mobile=VALUES(offers_mobile),offers_clinic=VALUES(offers_clinic),mobile_radius_km=VALUES(mobile_radius_km),travel_buffer_minutes=VALUES(travel_buffer_minutes),mobile_fee_cents=VALUES(mobile_fee_cents)');foreach($practitioners as $p){$travel=(int)($p['travel_buffer_minutes']??0);if($travel<0||$travel>240||$travel%15!==0)throw new ApiException(422,'validation_error','Travel buffers must be 15-minute increments up to 240 minutes.');if(!(bool)($p['offers_mobile']??false)&&!(bool)($p['offers_clinic']??true))throw new ApiException(422,'validation_error','Enable clinic visits or On-Site visits for each assigned practitioner.');
$radius=$p['mobile_radius_km']??null;if((bool)($p['offers_mobile']??false)&&(filter_var($radius,FILTER_VALIDATE_INT)===false||(int)$radius<1||(int)$radius>500))throw new ApiException(422,'validation_error','On-Site coverage radius must be between 1 and 500 km.');
$fee=$p['mobile_fee_cents']??0;if(filter_var($fee,FILTER_VALIDATE_INT)===false||(int)$fee<0||(int)$fee>10000000)throw new ApiException(422,'validation_error','Invalid On-Site fee.');
$up->execute(['service'=>$serviceId,'mobile'=>(bool)($p['offers_mobile']??false)?1:0,'clinic_visit'=>(bool)($p['offers_clinic']??true)?1:0,'radius'=>isset($p['mobile_radius_km'])?(int)$p['mobile_radius_km']:null,'travel'=>$travel,'fee'=>(int)($p['mobile_fee_cents']??0),'practitioner'=>(int)$p['practitioner_id'],'clinic'=>$actor->clinicId]);if($up->rowCount()===0)throw new ApiException(422,'invalid_practitioner','A selected practitioner was not found.');}$pdo->prepare('UPDATE service_locations SET active=0 WHERE service_id=:id')->execute(['id'=>$serviceId]);$ul=$pdo->prepare('INSERT INTO service_locations(service_id,location_id,active) SELECT :service,l.id,1 FROM locations l WHERE l.id=:location AND l.clinic_id=:clinic ON DUPLICATE KEY UPDATE active=1');foreach(array_unique(array_map('intval',$locations)) as $location)$ul->execute(['service'=>$serviceId,'location'=>$location,'clinic'=>$actor->clinicId]);$this->audit->write($actor->clinicId,$actor,$correlationId,'service.assignments.update','service',$serviceId,'success',['practitioners'=>count($practitioners),'locations'=>count($locations)]);$pdo->commit();return ['id'=>$serviceId];}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}

    public function createAvailability(AuthContext $actor,array $body,string $correlationId): array
    {
        $this->required($body,['practitioner_id','location_id','weekday','start_time','end_time','valid_from']);$this->scheduleAccess($actor,(int)$body['practitioner_id']);$this->ownedLocation($actor,(int)$body['location_id']);
        $statement=$this->database->connection()->prepare('INSERT INTO availability_rules(practitioner_id,location_id,weekday,start_time,end_time,valid_from,valid_until,recurrence_interval_weeks) VALUES(:p,:l,:weekday,:start,:end,:valid_from,:valid_until,:interval)');$statement->execute(['p'=>(int)$body['practitioner_id'],'l'=>(int)$body['location_id'],'weekday'=>(int)$body['weekday'],'start'=>$body['start_time'],'end'=>$body['end_time'],'valid_from'=>$body['valid_from'],'valid_until'=>$body['valid_until']??null,'interval'=>(int)($body['recurrence_interval_weeks']??1)]);return $this->created($actor,$correlationId,'availability_rule',(int)$this->database->connection()->lastInsertId());
    }
    public function availabilityRules(AuthContext $actor): array{$this->scheduleRole($actor);$own=$actor->hasAnyRole('practitioner')&&!$actor->hasAnyRole('super_admin','clinic_admin');$where=$own?' AND p.user_id=:actor':'';$params=['clinic'=>$actor->clinicId];if($own)$params['actor']=$actor->userId;$s=$this->database->connection()->prepare("SELECT a.id,a.practitioner_id,a.location_id,a.weekday,a.start_time,a.end_time,a.valid_from,a.valid_until,a.recurrence_interval_weeks,a.active,u.display_name practitioner_name,l.name location_name FROM availability_rules a JOIN practitioners p ON p.id=a.practitioner_id JOIN users u ON u.id=p.user_id JOIN locations l ON l.id=a.location_id WHERE u.clinic_id=:clinic{$where} ORDER BY u.display_name,a.weekday,a.start_time");$s->execute($params);return $s->fetchAll();}
    public function deleteAvailabilityRule(AuthContext $actor,int $id,string $cid): array{$this->scheduleRole($actor);$own=$actor->hasAnyRole('practitioner')&&!$actor->hasAnyRole('super_admin','clinic_admin');$sql='UPDATE availability_rules a JOIN practitioners p ON p.id=a.practitioner_id JOIN users u ON u.id=p.user_id SET a.active=0 WHERE a.id=:id AND a.active=1 AND u.clinic_id=:clinic'.($own?' AND p.user_id=:actor':'');$params=['id'=>$id,'clinic'=>$actor->clinicId];if($own)$params['actor']=$actor->userId;$s=$this->database->connection()->prepare($sql);$s->execute($params);if(!$s->rowCount())throw new ApiException(404,'availability_rule_not_found','Availability rule not found.');$this->audit->write($actor->clinicId,$actor,$cid,'availability_rule.archive','availability_rule',$id);return ['archived'=>true];}

    public function scheduleExceptions(AuthContext $actor): array{$this->scheduleRole($actor);$own=$actor->hasAnyRole('practitioner')&&!$actor->hasAnyRole('super_admin','clinic_admin');$where=$own?' AND p.user_id=:actor':'';$params=['clinic'=>$actor->clinicId];if($own)$params['actor']=$actor->userId;$pdo=$this->database->connection();$o=$pdo->prepare("SELECT o.id,o.practitioner_id,o.location_id,o.starts_at,o.ends_at,o.override_type type,o.reason,u.display_name practitioner_name,l.name location_name,'override' kind FROM availability_overrides o JOIN practitioners p ON p.id=o.practitioner_id JOIN users u ON u.id=p.user_id JOIN locations l ON l.id=o.location_id WHERE u.clinic_id=:clinic{$where}");$o->execute($params);$t=$pdo->prepare("SELECT t.id,t.practitioner_id,NULL location_id,t.starts_at,t.ends_at,t.reason_type type,t.notes reason,u.display_name practitioner_name,NULL location_name,'time_off' kind FROM time_off t JOIN practitioners p ON p.id=t.practitioner_id JOIN users u ON u.id=p.user_id WHERE u.clinic_id=:clinic{$where}");$t->execute($params);$rows=array_merge($o->fetchAll(),$t->fetchAll());usort($rows,fn($a,$b)=>strcmp($a['starts_at'],$b['starts_at']));return $rows;}
    public function createAvailabilityOverride(AuthContext $actor,array $body,string $cid): array{$this->required($body,['practitioner_id','location_id','starts_at','ends_at','override_type']);$this->scheduleAccess($actor,(int)$body['practitioner_id']);$this->ownedLocation($actor,(int)$body['location_id']);[$start,$end]=$this->utcInterval($body,(int)$body['location_id']);if(!in_array($body['override_type'],['available','blocked'],true))throw new ApiException(422,'validation_error','Invalid override type.');$s=$this->database->connection()->prepare('INSERT INTO availability_overrides(practitioner_id,location_id,starts_at,ends_at,override_type,reason,created_by) VALUES(:p,:l,:starts,:ends,:type,:reason,:actor)');$s->execute(['p'=>(int)$body['practitioner_id'],'l'=>(int)$body['location_id'],'starts'=>$start,'ends'=>$end,'type'=>$body['override_type'],'reason'=>$this->optional($body,'reason'),'actor'=>$actor->userId]);return $this->created($actor,$cid,'availability_override',(int)$this->database->connection()->lastInsertId());}
    public function createTimeOff(AuthContext $actor,array $body,string $cid): array{$this->required($body,['practitioner_id','location_id','starts_at','ends_at','reason_type']);$this->scheduleAccess($actor,(int)$body['practitioner_id']);$this->ownedLocation($actor,(int)$body['location_id']);[$start,$end]=$this->utcInterval($body,(int)$body['location_id']);if(!in_array($body['reason_type'],['vacation','sick','personal','other'],true))throw new ApiException(422,'validation_error','Invalid reason type.');$s=$this->database->connection()->prepare('INSERT INTO time_off(practitioner_id,starts_at,ends_at,reason_type,notes,created_by) VALUES(:p,:starts,:ends,:type,:notes,:actor)');$s->execute(['p'=>(int)$body['practitioner_id'],'starts'=>$start,'ends'=>$end,'type'=>$body['reason_type'],'notes'=>$this->optional($body,'notes'),'actor'=>$actor->userId]);return $this->created($actor,$cid,'time_off',(int)$this->database->connection()->lastInsertId());}
    public function deleteScheduleException(AuthContext $actor,string $table,int $id,string $cid): array{$this->scheduleRole($actor);if(!in_array($table,['availability_overrides','time_off'],true))throw new ApiException(500,'invalid_table','Invalid schedule table.');$own=$actor->hasAnyRole('practitioner')&&!$actor->hasAnyRole('super_admin','clinic_admin');$sql="DELETE x FROM {$table} x JOIN practitioners p ON p.id=x.practitioner_id JOIN users u ON u.id=p.user_id WHERE x.id=:id AND u.clinic_id=:clinic".($own?' AND p.user_id=:actor':'');$params=['id'=>$id,'clinic'=>$actor->clinicId];if($own)$params['actor']=$actor->userId;$s=$this->database->connection()->prepare($sql);$s->execute($params);if(!$s->rowCount())throw new ApiException(404,'schedule_exception_not_found','Schedule exception not found.');$this->audit->write($actor->clinicId,$actor,$cid,'schedule_exception.delete',$table,$id);return ['deleted'=>true];}

    private function admin(AuthContext $actor): void{if(!$actor->hasAnyRole('super_admin','clinic_admin'))throw new ApiException(403,'forbidden','Administrator access is required.');}
    private function superAdmin(AuthContext $actor): void{if(!$actor->hasAnyRole('super_admin'))throw new ApiException(403,'forbidden','Super administrator access is required.');}
    private function required(array $body,array $fields): void{foreach($fields as $field)if(!array_key_exists($field,$body)||$body[$field]===''||$body[$field]===null)throw new ApiException(422,'validation_error',"{$field} is required.",[$field=>'Required']);}
    private function optional(array $body,string $field): ?string{$value=trim((string)($body[$field]??''));return $value===''?null:$value;}
    private function clinic(int $clinicId): array{$statement=$this->database->connection()->prepare('SELECT name,legal_name,email,phone FROM clinics WHERE id=:clinic');$statement->execute(['clinic'=>$clinicId]);$clinic=$statement->fetch();if(!$clinic)throw new ApiException(404,'clinic_not_found','Clinic not found.');return $clinic;}
    private function ownedLocation(AuthContext $actor,int $locationId): void{$statement=$this->database->connection()->prepare('SELECT 1 FROM locations WHERE id=:id AND clinic_id=:clinic');$statement->execute(['id'=>$locationId,'clinic'=>$actor->clinicId]);if(!$statement->fetchColumn())throw new ApiException(404,'location_not_found','Location not found.');}
    private function ownedServiceCategory(AuthContext $actor,mixed $categoryId): ?int{if($categoryId===null||$categoryId==='')return null;if(filter_var($categoryId,FILTER_VALIDATE_INT)===false||(int)$categoryId<=0)throw new ApiException(422,'validation_error','Choose a valid service category.',['category_id'=>'Invalid category']);$statement=$this->database->connection()->prepare('SELECT 1 FROM service_categories WHERE id=:id AND clinic_id=:clinic');$statement->execute(['id'=>(int)$categoryId,'clinic'=>$actor->clinicId]);if(!$statement->fetchColumn())throw new ApiException(422,'validation_error','Choose a valid service category.',['category_id'=>'Category not found']);return (int)$categoryId;}
    private function validateLocation(array $body): void{if(strlen(trim((string)$body['name']))>150)throw new ApiException(422,'validation_error','The location name is too long.',['name'=>'Maximum 150 characters']);if(!in_array((string)$body['timezone'],timezone_identifiers_list(),true))throw new ApiException(422,'validation_error','Enter a valid timezone.',['timezone'=>'Invalid timezone']);foreach(['address_line1'=>190,'address_line2'=>190,'city'=>100,'province'=>100,'postal_code'=>20,'phone'=>40] as $field=>$limit)if(strlen(trim((string)($body[$field]??'')))>$limit)throw new ApiException(422,'validation_error',"{$field} is too long.",[$field=>"Maximum {$limit} characters"]);}
    private function validateRoom(array $body): void{$name=trim((string)$body['name']);$turnover=(int)($body['turnover_minutes']??0);if($name===''||strlen($name)>100)throw new ApiException(422,'validation_error','Enter a valid room name.',['name'=>'Required; maximum 100 characters']);if(strlen(trim((string)($body['room_type']??'')))>80)throw new ApiException(422,'validation_error','The room type is too long.',['room_type'=>'Maximum 80 characters']);if($turnover<0||$turnover>240||$turnover%5!==0)throw new ApiException(422,'validation_error','Turnover time must be a 5-minute increment between 0 and 240.',['turnover_minutes'=>'Invalid turnover time']);}
    public static function durationOptions(array $body): array
    {
        $raw=$body['duration_options']??null;
        if($raw===null&&is_array($body['durations']??null))$raw=array_map(static fn($minutes)=>['minutes'=>$minutes,'price_cents'=>$body['price_cents']??null],$body['durations']);
        if(!is_array($raw)||$raw===[])throw new ApiException(422,'validation_error','Add at least one duration and price.');
        $options=[];
        foreach($raw as $option){
            if(!is_array($option)||filter_var($option['minutes']??null,FILTER_VALIDATE_INT)===false||filter_var($option['price_cents']??null,FILTER_VALIDATE_INT)===false)throw new ApiException(422,'validation_error','Each duration needs a valid time and price.');
            $minutes=(int)$option['minutes'];$price=(int)$option['price_cents'];
            if($minutes<=0||$minutes>480||$minutes%15!==0)throw new ApiException(422,'validation_error','Durations must be 15-minute increments up to 480 minutes.');
            if($price<0||$price>10000000)throw new ApiException(422,'validation_error','Each duration needs a valid price.');
            if(isset($options[$minutes]))throw new ApiException(422,'validation_error','Each duration can be listed only once.');
            $options[$minutes]=['minutes'=>$minutes,'price_cents'=>$price];
        }
        ksort($options);return array_values($options);
    }
    private function validateService(array $body,array $options): void{$this->required($body,['name']);$name=trim((string)$body['name']);if($name===''||strlen($name)>150)throw new ApiException(422,'validation_error','Enter a valid service name.');if($options===[])throw new ApiException(422,'validation_error','Add at least one duration and price.');foreach(['buffer_before_minutes','buffer_after_minutes'] as $f)if((int)($body[$f]??0)<0||(int)($body[$f]??0)%15!==0)throw new ApiException(422,'validation_error','Buffers must be non-negative 15-minute increments.');}
    private function scheduleRole(AuthContext $actor): void{if(!$actor->hasAnyRole('super_admin','clinic_admin','practitioner'))throw new ApiException(403,'forbidden','Schedule access is required.');}
    private function scheduleAccess(AuthContext $actor,int $practitionerId): void{$this->scheduleRole($actor);$sql='SELECT 1 FROM practitioners p JOIN users u ON u.id=p.user_id WHERE p.id=:p AND u.clinic_id=:clinic';$params=['p'=>$practitionerId,'clinic'=>$actor->clinicId];if($actor->hasAnyRole('practitioner')&&!$actor->hasAnyRole('super_admin','clinic_admin')){$sql.=' AND p.user_id=:actor';$params['actor']=$actor->userId;}$s=$this->database->connection()->prepare($sql);$s->execute($params);if(!$s->fetchColumn())throw new ApiException(403,'forbidden','You cannot manage that practitioner schedule.');}
    private function utcInterval(array $body,int $locationId): array{$s=$this->database->connection()->prepare('SELECT timezone FROM locations WHERE id=:id');$s->execute(['id'=>$locationId]);$timezone=$s->fetchColumn();try{$zone=new \DateTimeZone((string)$timezone);$start=new \DateTimeImmutable((string)$body['starts_at'],$zone);$end=new \DateTimeImmutable((string)$body['ends_at'],$zone);}catch(\Throwable){throw new ApiException(422,'validation_error','Enter valid local start and end times.');}if($start>=$end)throw new ApiException(422,'validation_error','Start must be before end.');$utc=new \DateTimeZone('UTC');return [$start->setTimezone($utc)->format('Y-m-d H:i:s'),$end->setTimezone($utc)->format('Y-m-d H:i:s')];}
    private function created(AuthContext $actor,string $correlationId,string $type,int $id): array{$this->audit->write($actor->clinicId,$actor,$correlationId,$type.'.create',$type,$id);return ['id'=>$id];}
}
