<?php
declare(strict_types=1);
namespace Wellness\Service;
use Wellness\Auth\AuthContext;use Wellness\Database;use Wellness\Http\ApiException;
final class ProfileService{
 public function __construct(private readonly Database $db,private readonly AuditLogger $audit){}
 public function avatar(AuthContext $actor,?int $target=null):array{$uid=$this->target($actor,$target);$s=$this->db->connection()->prepare('SELECT mime_type,image_data,updated_at FROM user_profile_images WHERE user_id=:user');$s->execute(['user'=>$uid]);$r=$s->fetch();return $r?['mime_type'=>$r['mime_type'],'image_base64'=>base64_encode($r['image_data']),'updated_at'=>$r['updated_at']]:['mime_type'=>null,'image_base64'=>null,'updated_at'=>null];}
 public function save(AuthContext $actor,array $body,string $cid,?int $target=null):array{$uid=$this->target($actor,$target);$encoded=(string)($body['image_base64']??'');if($encoded===''||strlen($encoded)>750000)throw new ApiException(422,'validation_error','Choose an image smaller than 500 KB.');$data=base64_decode($encoded,true);if($data===false||strlen($data)>500000)throw new ApiException(422,'validation_error','The image is invalid or too large.');$info=@getimagesizefromstring($data);if($info===false||($info['mime']??'')!=='image/webp'||$info[0]<64||$info[1]<64||$info[0]>512||$info[1]>512)throw new ApiException(422,'validation_error','The image must be WebP and between 64 and 512 pixels.');$s=$this->db->connection()->prepare("INSERT INTO user_profile_images(user_id,mime_type,image_data,byte_size,content_hash,updated_by) VALUES(:user,'image/webp',:data,:size,:hash,:actor) ON DUPLICATE KEY UPDATE image_data=VALUES(image_data),byte_size=VALUES(byte_size),content_hash=VALUES(content_hash),updated_by=VALUES(updated_by)");$s->bindValue(':user',$uid,\PDO::PARAM_INT);$s->bindValue(':data',$data,\PDO::PARAM_LOB);$s->bindValue(':size',strlen($data),\PDO::PARAM_INT);$s->bindValue(':hash',hash('sha256',$data));$s->bindValue(':actor',$actor->userId,\PDO::PARAM_INT);$s->execute();$this->audit->write($actor->clinicId,$actor,$cid,'profile.avatar.update','user',$uid,'success',['moderated'=>$uid!==$actor->userId]);return ['updated'=>true];}
 public function delete(AuthContext $actor,string $cid,?int $target=null):array{$uid=$this->target($actor,$target);$s=$this->db->connection()->prepare('DELETE FROM user_profile_images WHERE user_id=:user');$s->execute(['user'=>$uid]);$this->audit->write($actor->clinicId,$actor,$cid,'profile.avatar.delete','user',$uid,'success',['moderated'=>$uid!==$actor->userId]);return ['deleted'=>$s->rowCount()>0];}
 private function target(AuthContext $a,?int $id):int{if($id===null||$id===$a->userId)return $a->userId;if(!$a->hasAnyRole('super_admin'))throw new ApiException(403,'forbidden','Super administrator access is required.');$s=$this->db->connection()->prepare('SELECT 1 FROM users WHERE id=:id AND clinic_id=:clinic');$s->execute(['id'=>$id,'clinic'=>$a->clinicId]);if(!$s->fetchColumn())throw new ApiException(404,'user_not_found','User not found.');return $id;}
}
