import { useEffect,useState,type ChangeEvent } from 'react';
import { Alert,Avatar,Box,Button,Paper,Stack,Typography } from '@mui/material';
import { ImagePlus,Trash2 } from 'lucide-react';
import { useStaffAuth } from '../auth/AuthProvider';
import { useTranslation } from 'react-i18next';
import type { TFunction } from 'i18next';
import { apiErrorMessage } from '../shared/api';
const api=import.meta.env.VITE_API_BASE_URL??'http://localhost:8080/api/v1';
async function normalized(file:File,t:TFunction):Promise<string>{if(!file.type.startsWith('image/'))throw new Error(t('Choose an image file.'));if(file.size>5_000_000)throw new Error(t('Choose an image smaller than 5 MB.'));const bitmap=await createImageBitmap(file);const size=320,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const context=canvas.getContext('2d');if(!context)throw new Error(t('Image processing is unavailable.'));const crop=Math.min(bitmap.width,bitmap.height),x=(bitmap.width-crop)/2,y=(bitmap.height-crop)/2;context.drawImage(bitmap,x,y,crop,crop,0,0,size,size);bitmap.close();return canvas.toDataURL('image/webp',.82).split(',')[1];}
export function ProfileSettings(){const{t}=useTranslation();const {account,getAccessToken}=useStaffAuth();const [src,setSrc]=useState<string>();const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const load=async()=>{const token=await getAccessToken();const r=await fetch(`${api}/profile/avatar`,{headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok)throw new Error(apiErrorMessage(b,r.status,t('Unable to load profile image.')));setSrc(b.data.image_base64?`data:${b.data.mime_type};base64,${b.data.image_base64}`:undefined);};useEffect(()=>{void load().catch(()=>{});},[]);
 const upload=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');setMessage('');try{const image_base64=await normalized(file,t),token=await getAccessToken();const r=await fetch(`${api}/profile/avatar`,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({image_base64})}),b=await r.json();if(!r.ok)throw new Error(apiErrorMessage(b,r.status,t('Unable to upload image.')));await load();window.dispatchEvent(new Event('avatar-updated'));setMessage(t('Profile image updated.'));}catch(c){setError(c instanceof Error?c.message:t('Unable to upload image.'));}finally{setBusy(false);e.target.value='';}};
 const remove=async()=>{setBusy(true);setError('');try{const token=await getAccessToken(),r=await fetch(`${api}/profile/avatar`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}}),b=await r.json();if(!r.ok)throw new Error(apiErrorMessage(b,r.status,t('Unable to remove image.')));setSrc(undefined);window.dispatchEvent(new Event('avatar-updated'));setMessage(t('Profile image removed.'));}catch(c){setError(c instanceof Error?c.message:t('Unable to remove image.'));}finally{setBusy(false);}};
 return <Paper variant="outlined" sx={{p:{xs:2,md:3}}}><Typography variant="h5" mb={.5}>{t('Account profile')}</Typography><Typography color="text.secondary" mb={3}>{t('Your profile image belongs to this application and is not synchronized with Microsoft.')}</Typography><Stack direction={{xs:'column',sm:'row'}} spacing={3} alignItems={{sm:'center'}}><Avatar src={src} sx={{width:112,height:112,bgcolor:'primary.main',fontSize:32}}>{account?.name?.split(' ').map(x=>x[0]).slice(0,2).join('')}</Avatar><Stack spacing={1.5}><Box><Typography fontWeight={700}>{account?.name}</Typography><Typography color="text.secondary">{account?.username}</Typography></Box><Stack direction="row" spacing={1}><Button component="label" variant="contained" startIcon={<ImagePlus size={17}/>} disabled={busy}>{t('Choose image')}<input hidden type="file" accept="image/*" onChange={upload}/></Button>{src&&<Button color="error" startIcon={<Trash2 size={17}/>} onClick={remove} disabled={busy}>{t('Remove')}</Button>}</Stack><Typography variant="caption" color="text.secondary">{t('Images are cropped square and securely converted before upload. Maximum source size: 5 MB.')}</Typography></Stack></Stack>{message&&<Alert severity="success" sx={{mt:2}}>{message}</Alert>}{error&&<Alert severity="error" sx={{mt:2}}>{error}</Alert>}</Paper>}
