import { useEffect, useState } from 'react';
import { Alert, Button, Checkbox, CircularProgress, FormControlLabel, MenuItem, Paper, Stack, TextField, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { useUnsavedChanges } from '../shared/UnsavedChanges';
import { useFormRequest } from './api';
import type { Definition, Question } from './FormTasks';
type Template = { id: number; name: string; form_type: string; version: number; owner_practitioner_id: number; definition: Definition; service_ids: number[]; practitioner_name: string };
type Option = { id: number; name?: string; display_name?: string };
type Data = { items: Template[]; practitioners: Option[]; services: Option[]; has_more: boolean; can_author: boolean };
const firstQuestion = (): Question => ({ id: 'q1', label: '', label_fr: '', type: 'text', required: true });
export function FormTemplates() {
  const { t } = useTranslation(), request = useFormRequest();
  const [data, setData] = useState<Data | null>(null), [page, setPage] = useState(1), [reload, setReload] = useState(0), [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [error, setError] = useState('');
  const [editing, setEditing] = useState(false), [previous, setPrevious] = useState<Template | null>(null), [name, setName] = useState(''), [type, setType] = useState('intake'), [owner, setOwner] = useState(''), [services, setServices] = useState<number[]>([]), [definition, setDefinition] = useState<Definition>({ instructions: '', instructions_fr: '', questions: [firstQuestion()] }), [key, setKey] = useState(() => crypto.randomUUID()), [history, setHistory] = useState<Template[] | null>(null);
  useUnsavedChanges(editing);
  useEffect(() => { const controller = new AbortController(); setLoading(true); setError(''); void request(`/forms/templates?page=${page}`, { signal: controller.signal }).then(result => { if (!controller.signal.aborted) setData(result); }).catch(cause => { if (!controller.signal.aborted) setError(cause.message); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); return () => controller.abort(); }, [request, page, reload]);
  const edit = (template?: Template) => { setPrevious(template ?? null); setName(template?.name ?? ''); setType(template?.form_type ?? 'intake'); setOwner(String(template?.owner_practitioner_id ?? data?.practitioners[0]?.id ?? '')); setServices(template?.service_ids ?? []); setDefinition(template ? structuredClone(template.definition) : { instructions: '', instructions_fr: '', questions: [firstQuestion()] }); setEditing(true); setKey(crypto.randomUUID()); setError(''); setHistory(null); };
  const question = (id: string, changes: Partial<Question>) => setDefinition(d => ({ ...d, questions: d.questions.map(q => q.id === id ? { ...q, ...changes } : q) }));
  const publish = async () => {
    setBusy(true); setError('');
    try { const result = await request(previous ? `/forms/templates/${previous.id}/versions` : '/forms/templates', { method: 'POST', body: JSON.stringify({ name, form_type: type, owner_practitioner_id: Number(owner), definition, service_ids: services, expected_version: previous ? Number(previous.version) : 0, idempotency_key: key }) }); if (!Number.isSafeInteger(result.id) || result.id < 1) throw new Error(t('Invalid form response.')); setUncertain(false); setEditing(false); setReload(v => v + 1); }
    catch (cause) { const status = Number((cause as { status?: number }).status); setUncertain(!status || status >= 500); setError((cause as Error).message); }
    finally { setBusy(false); }
  };
  const versions = async (template: Template) => { setBusy(true); setError(''); try { setHistory((await request(`/forms/templates/${template.id}/history`)).items); } catch (cause) { setError((cause as Error).message); } finally { setBusy(false); } };
  return <Stack spacing={2}><Typography variant="h5">{t('Intake and consent forms')}</Typography><Alert severity="info">{t('Publishing creates an immutable version. Existing assignments keep their original questions.')}</Alert>{error && <Alert severity="error">{error}</Alert>}
    {editing ? <Stack component="form" spacing={2} onSubmit={event => { event.preventDefault(); void publish(); }}>
      {uncertain && <Alert severity="warning">{t('Confirmation is uncertain. Retry the same answers before making changes.')}</Alert>}
      <TextField label={t('Form name')} required value={name} disabled={busy || uncertain} inputProps={{ maxLength: 190 }} onChange={event => setName(event.target.value)}/>
      <TextField select label={t('Form type')} value={type} disabled={busy || uncertain} onChange={event => setType(event.target.value)}>{['intake', 'consent', 'follow_up', 'questionnaire'].map(value => <MenuItem key={value} value={value}>{t(`Form type: ${value}`)}</MenuItem>)}</TextField>
      <TextField select required label={t('Assigned practitioner')} value={owner} disabled={busy || uncertain || previous !== null} onChange={event => { setOwner(event.target.value); setServices([]); }}>{data?.practitioners.map(p => <MenuItem key={p.id} value={p.id}>{p.display_name}</MenuItem>)}</TextField>
      <TextField label={t('Instructions (English)')} multiline minRows={2} value={definition.instructions} disabled={busy || uncertain} inputProps={{ maxLength: 5000 }} onChange={event => setDefinition(d => ({ ...d, instructions: event.target.value }))}/>
      <TextField label={t('Instructions (French)')} multiline minRows={2} value={definition.instructions_fr} disabled={busy || uncertain} inputProps={{ maxLength: 5000 }} onChange={event => setDefinition(d => ({ ...d, instructions_fr: event.target.value }))}/>
      {definition.questions.map((q, index) => <Paper key={q.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography>{t('Question {{number}}', { number: index + 1 })}</Typography><TextField required label={t('Question (English)')} value={q.label} disabled={busy || uncertain} inputProps={{ maxLength: 500 }} onChange={event => question(q.id, { label: event.target.value })}/><TextField label={t('Question (French)')} value={q.label_fr} disabled={busy || uncertain} inputProps={{ maxLength: 500 }} onChange={event => question(q.id, { label_fr: event.target.value })}/><TextField select label={t('Answer type')} value={q.type} disabled={busy || uncertain} onChange={event => question(q.id, { type: event.target.value as Question['type'], required: event.target.value === 'consent' || q.required })}>{['text', 'yes_no', 'consent'].map(value => <MenuItem key={value} value={value}>{t(`Answer type: ${value}`)}</MenuItem>)}</TextField><FormControlLabel label={t('Required')} control={<Checkbox checked={q.required} disabled={busy || uncertain || q.type === 'consent'} onChange={event => question(q.id, { required: event.target.checked })}/>}/><Button disabled={busy || uncertain || definition.questions.length === 1} onClick={() => setDefinition(d => ({ ...d, questions: d.questions.filter(item => item.id !== q.id) }))}>{t('Remove question')}</Button></Stack></Paper>)}
      <Button disabled={busy || uncertain || definition.questions.length >= 30} onClick={() => setDefinition(d => ({ ...d, questions: [...d.questions, { ...firstQuestion(), id: `q${crypto.randomUUID().replaceAll('-', '').slice(0, 20)}` }] }))}>{t('Add question')}</Button>
      <Typography>{t('Automatically assign on new bookings for these services with this practitioner:')}</Typography>
      {data?.services.map(s => <FormControlLabel key={s.id} label={s.name} control={<Checkbox checked={services.includes(s.id)} disabled={busy || uncertain} onChange={event => setServices(ids => event.target.checked ? [...ids, s.id] : ids.filter(id => id !== s.id))}/>}/>)}
      <Stack direction="row" spacing={1}><Button type="submit" variant="contained" disabled={busy || !owner}>{t(uncertain ? 'Retry confirmation' : previous ? 'Publish new version' : 'Publish form')}</Button><Button disabled={busy || uncertain} onClick={() => { if (window.confirm(t('Discard this unpublished form?'))) setEditing(false); }}>{t('Cancel')}</Button></Stack>
    </Stack> : <>{loading && <CircularProgress aria-label={t('Loading forms')}/>}<Button disabled={busy || !data?.can_author} variant="contained" onClick={() => edit()}>{t('Create form')}</Button>{data && !data.items.length && <Typography>{t('No form templates yet.')}</Typography>}{data?.items.map(f => <Paper key={f.id} variant="outlined" sx={{ p: 2 }}><Stack spacing={1}><Typography fontWeight={700}>{f.name}</Typography><Typography>{f.practitioner_name} · {t('Form version {{version}}', { version: f.version })}</Typography><Stack direction="row" gap={1} flexWrap="wrap"><Button disabled={busy || !data.can_author} onClick={() => edit(f)}>{t('Create new version')}</Button><Button disabled={busy || !data.can_author} onClick={() => void versions(f)}>{t('Version history')}</Button></Stack></Stack></Paper>)}<Stack direction="row" spacing={1}><Button disabled={loading || page === 1} onClick={() => setPage(p => p - 1)}>{t('Previous')}</Button><Button disabled={loading || !data?.has_more} onClick={() => setPage(p => p + 1)}>{t('Next')}</Button><Button disabled={loading || busy} onClick={() => setReload(v => v + 1)}>{t('Refresh')}</Button></Stack></>}
    {history && <Paper variant="outlined" sx={{ p: 2 }}><Stack spacing={2}><Typography variant="h6">{t('Version history')}</Typography>{history.map(version => <Stack key={version.id}><Typography fontWeight={700}>{t('Form version {{version}}', { version: version.version })} · {version.name}</Typography>{version.definition.questions.map(q => <Typography key={q.id}>{q.label}{q.label_fr ? ` / ${q.label_fr}` : ''}</Typography>)}</Stack>)}<Button onClick={() => setHistory(null)}>{t('Close')}</Button></Stack></Paper>}
  </Stack>;
}
