import { Alert, TextField, withFormValidation, useFormValidation } from '../shared/FormValidation';
import { useState } from 'react';
import { Button, Dialog, DialogActions, DialogContent, DialogTitle, MenuItem, Stack, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { useUnsavedChanges } from '../shared/UnsavedChanges';
export type FormDocument = { format: 'wellness-form'; format_version: 1; name: string; form_type: string; definition: import('./FormTasks').Definition };
function FormSourceDialogForm({ initial, importing, practitioners, onApply, onClose }: { initial: string; importing: boolean; practitioners: { id: number; display_name?: string }[]; onApply: (raw: string, owner: number) => Promise<void>; onClose: () => void }) {
  const formValidation = useFormValidation();
  const { t } = useTranslation();
  const [raw, setRaw] = useState(initial), [owner, setOwner] = useState(String(practitioners[0]?.id ?? '')), [busy, setBusy] = useState(false), [uncertain, setUncertain] = useState(false), [error, setError] = useState('');
  useUnsavedChanges(raw !== initial || uncertain);
  const close = () => { if (!busy && !uncertain && (raw === initial || window.confirm(t('Discard unapplied source changes?')))) onClose(); };
  const apply = async () => { setBusy(true); (formValidation.clear(), setError('')); try { await onApply(raw, Number(owner)); onClose(); } catch (cause) { formValidation.capture(cause); setError((cause as Error).message); const status = Number((cause as { status?: number }).status); setUncertain(importing && (!status || status >= 500)); } finally { setBusy(false); } };
  const download = () => { const url = URL.createObjectURL(new Blob([raw], { type: 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = 'form-source.json'; link.click(); URL.revokeObjectURL(url); };
  return <Dialog open fullWidth maxWidth="md" onClose={close}><DialogTitle>{t(importing ? 'Import form JSON' : 'View source')}</DialogTitle><DialogContent><Stack spacing={2} sx={{ pt: 1 }}><Typography>{t('Source changes stay unpublished. Apply them to the editor, then save a draft or publish when ready.')}</Typography>{error && <Alert severity="error">{error}</Alert>}{uncertain && <Alert severity="warning">{t('Confirmation is uncertain. Retry the same answers before making changes.')}</Alert>}{importing && <><TextField name="owner" select label={t('Assigned practitioner')} value={owner} disabled={busy || uncertain} onChange={event => setOwner(event.target.value)}>{practitioners.map(p => <MenuItem key={p.id} value={p.id}>{p.display_name}</MenuItem>)}</TextField><Button component="label" disabled={busy || uncertain}>{t('Choose JSON file')}<input hidden type="file" accept=".json,application/json" onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (!file) return; if (file.size > 65536) { setError(t('Form JSON must be no larger than 64 KB.')); return; } void file.text().then(setRaw).catch(() => setError(t('Unable to read the JSON file.'))); }}/></Button></>}<TextField name="raw" label={t('Form JSON source')} value={raw} disabled={busy || uncertain} multiline minRows={12} maxRows={24} inputProps={{ spellCheck: false }} sx={{ '& textarea': { fontFamily: 'monospace', fontSize: 13 } }} onChange={event => setRaw(event.target.value)}/></Stack></DialogContent><DialogActions sx={{ flexWrap: 'wrap', gap: 1 }}><Button onClick={download}>{t('Download JSON')}</Button><Button disabled={busy || uncertain} onClick={close}>{t('Close')}</Button><Button variant="contained" disabled={busy || (importing && !owner)} onClick={() => void apply()}>{t(uncertain ? 'Retry confirmation' : importing ? 'Import as draft' : 'Apply source')}</Button></DialogActions></Dialog>;
}
export const FormSourceDialog = withFormValidation(FormSourceDialogForm);
