import { useCallback, useEffect, useRef, useState, type ChangeEvent } from 'react';
import { Alert, Box, Button, Chip, Dialog, DialogActions, DialogContent, DialogTitle, Divider, List, ListItemButton, ListItemText, Paper, Stack, Typography } from '@mui/material';
import { FileJson, History, Power, RotateCcw, Upload } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { useStaffAuth } from '../auth/AuthProvider';
import { apiErrorMessage, normalizeNumericIds } from '../shared/api';

const api=import.meta.env.VITE_API_BASE_URL??'http://localhost:8080/api/v1';
type Definition={id:string;workspaces:string[];renderer:string;dataProjection:string;requiredCapability:string;title:{en:string;fr:string};description:{en:string;fr:string};icon:string;sizes:string[];defaultSize:string;parameters:Record<string,unknown>};
type Widget={id:string;source:'built_in'|'custom';enabled:boolean;active_version:number|null;has_override:boolean;definition:Definition};
type Version={version_number:number;definition_hash:string;created_at:string;created_by:string;active:boolean;definition:Definition};

export function DashboardWidgetAdmin(){
  const {t}=useTranslation();const {getAccessToken}=useStaffAuth();const input=useRef<HTMLInputElement>(null);const [items,setItems]=useState<Widget[]>([]),[selected,setSelected]=useState<string|null>(null),[upload,setUpload]=useState<Definition|null>(null),[duplicate,setDuplicate]=useState(false),[versions,setVersions]=useState<Version[]|null>(null),[versionsBuiltIn,setVersionsBuiltIn]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const request=useCallback(async(path:string,init:RequestInit={})=>{const token=await getAccessToken();const response=await fetch(`${api}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...init.headers}});const text=await response.text();let body;try{body=JSON.parse(text);}catch{throw Object.assign(new Error(t('The server returned an unreadable response (HTTP {{status}}). Try again or contact the administrator.',{status:response.status})),{code:'invalid_response'});}if(!response.ok)throw Object.assign(new Error(apiErrorMessage(body,response.status,t('Request failed (HTTP {{status}}).',{status:response.status}))),{code:body?.error?.code??'request_failed'});return normalizeNumericIds(body.data);},[getAccessToken,t]);
  const load=useCallback(async(preferred?:string)=>{setError('');try{const data:Widget[]=await request('/admin/dashboard-widgets');setItems(data);setSelected(preferred??data[0]?.id??null);}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to load dashboard widgets.'));}},[request,t]);
  useEffect(()=>{void load();},[load]);
  const chooseFile=async(event:ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';setError('');setNotice('');setDuplicate(false);if(!file)return;if(file.size>64*1024){setError(t('Widget JSON files must be 64 KB or smaller.'));return;}try{const parsed=JSON.parse(await file.text());if(!parsed||Array.isArray(parsed)||typeof parsed!=='object')throw new Error();setUpload(parsed);}catch{setError(t('The selected file is not valid widget JSON.'));}};
  const publish=async(confirm=false)=>{if(!upload)return;setBusy(true);setError('');try{const result=await request('/admin/dashboard-widgets',{method:'POST',body:JSON.stringify({definition:upload,confirm_replace:confirm})});setUpload(null);setDuplicate(false);setNotice(t(result.replaced?'Widget version {{version}} published.':'Widget uploaded and published.',{version:result.version}));await load(result.id);}catch(cause){if((cause as {code?:string})?.code==='widget_exists'){setDuplicate(true);}else setError(cause instanceof Error?cause.message:t('Unable to publish widget.'));}finally{setBusy(false);}};
  const openVersions=async()=>{if(!selected)return;setBusy(true);setError('');try{const data=await request(`/admin/dashboard-widgets/${selected}/versions`);setVersions(data.versions);setVersionsBuiltIn(Boolean(data.built_in));}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to load widget versions.'));}finally{setBusy(false);}};
  const restore=async(version:number)=>{if(!selected)return;setBusy(true);setError('');try{await request(`/admin/dashboard-widgets/${selected}/versions/${version}/restore`,{method:'POST',body:'{}'});setVersions(null);setNotice(t(version===0?'System widget definition restored.':'Widget version {{version}} restored.',{version}));await load(selected);}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to restore widget version.'));}finally{setBusy(false);}};
  const toggle=async()=>{const item=items.find(value=>value.id===selected);if(!item)return;setBusy(true);setError('');try{await request(`/admin/dashboard-widgets/${item.id}`,{method:'PATCH',body:JSON.stringify({enabled:!item.enabled})});setNotice(t(item.enabled?'Widget disabled.':'Widget enabled.'));await load(item.id);}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to update widget.'));}finally{setBusy(false);}};
  const item=items.find(value=>value.id===selected)??null;
  return <Stack spacing={3}>
    <Alert severity="info">{t('Upload only trusted widget JSON. The server accepts approved renderers, projections, permissions, filters, routes, and icons; executable code and SQL are never allowed.')}</Alert>
    {error&&<Alert severity="error" onClose={()=>setError('')}>{error}</Alert>}{notice&&<Alert severity="success" onClose={()=>setNotice('')}>{notice}</Alert>}
    <Paper variant="outlined"><Stack direction="row" gap={1} flexWrap="wrap" p={1.5}><Button startIcon={<Upload size={18}/>} variant="contained" disabled={busy} onClick={()=>input.current?.click()}>{t('Upload widget JSON')}</Button><input ref={input} hidden type="file" accept="application/json,.json" onChange={chooseFile}/><Button startIcon={<History size={18}/>} disabled={!item||busy} onClick={()=>void openVersions()}>{t('Versions')}</Button><Button startIcon={<Power size={18}/>} disabled={!item||busy} color={item?.enabled?'warning':'success'} onClick={()=>void toggle()}>{t(item?.enabled?'Disable':'Enable')}</Button></Stack></Paper>
    <Stack direction={{xs:'column',md:'row'}} spacing={3} alignItems="flex-start"><Paper variant="outlined" sx={{width:{xs:'100%',md:360},overflow:'hidden'}}><List disablePadding aria-label={t('Dashboard widgets')}>{items.map(value=><ListItemButton divider key={value.id} selected={selected===value.id} onClick={()=>setSelected(value.id)}><ListItemText primary={value.definition.title.en} secondary={`${value.id} · ${value.source==='built_in'?t('Built-in'):t('Custom')} · ${value.enabled?t('Enabled'):t('Disabled')}`}/></ListItemButton>)}</List></Paper>
      {item&&<Paper variant="outlined" sx={{p:3,flex:1,width:'100%'}}><Stack spacing={2}><Stack direction="row" justifyContent="space-between" gap={2}><Box><Typography variant="overline" color="primary.main">{item.id}</Typography><Typography variant="h5">{item.definition.title.en}</Typography><Typography lang="fr" color="text.secondary">{item.definition.title.fr}</Typography></Box><Stack direction="row" gap={1}><Chip label={item.enabled?t('Enabled'):t('Disabled')} color={item.enabled?'success':'default'}/><Chip label={item.source==='built_in'?t('Built-in'):t('Custom')} variant="outlined"/></Stack></Stack><Divider/><Typography>{item.definition.description.en}</Typography><Typography lang="fr" color="text.secondary">{item.definition.description.fr}</Typography><Typography><strong>{t('Workspace')}:</strong> {item.definition.workspaces.join(', ')}</Typography><Typography><strong>{t('Renderer')}:</strong> {item.definition.renderer}</Typography><Typography><strong>{t('Data projection')}:</strong> {item.definition.dataProjection}</Typography><Typography><strong>{t('Required capability')}:</strong> {item.definition.requiredCapability}</Typography><Typography><strong>{t('Active version')}:</strong> {item.active_version||t('System default')}</Typography><Paper component="pre" variant="outlined" sx={{p:2,overflow:'auto',fontSize:12,whiteSpace:'pre-wrap'}}>{JSON.stringify(item.definition,null,2)}</Paper></Stack></Paper>}
    </Stack>
    <Dialog open={Boolean(upload)} onClose={busy?undefined:()=>{setUpload(null);setDuplicate(false);}} fullWidth maxWidth="md"><DialogTitle>{t(duplicate?'Replace existing widget?':'Review widget upload')}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{duplicate&&<Alert severity="warning">{t('A widget with ID “{{id}}” already exists. Publishing creates a recoverable new version and makes it active.',{id:upload?.id})}</Alert>}<Paper component="pre" variant="outlined" sx={{p:2,maxHeight:480,overflow:'auto',fontSize:12,whiteSpace:'pre-wrap'}}>{JSON.stringify(upload,null,2)}</Paper></Stack></DialogContent><DialogActions><Button disabled={busy} onClick={()=>{setUpload(null);setDuplicate(false);}}>{t('Cancel')}</Button><Button variant="contained" startIcon={<FileJson size={18}/>} disabled={busy} onClick={()=>void publish(duplicate)}>{t(duplicate?'Publish new version':'Validate and publish')}</Button></DialogActions></Dialog>
    <Dialog open={versions!==null} onClose={busy?undefined:()=>setVersions(null)} fullWidth maxWidth="md"><DialogTitle>{t('Widget versions')}</DialogTitle><DialogContent><Stack spacing={2} pt={1}>{versionsBuiltIn&&<Paper variant="outlined" sx={{p:2}}><Stack direction="row" alignItems="center" justifyContent="space-between" gap={2}><Box><Typography fontWeight={700}>{t('System default')}</Typography><Typography color="text.secondary">{t('Restore the definition included with the application.')}</Typography></Box><Button startIcon={<RotateCcw size={17}/>} disabled={busy||item?.active_version===0} onClick={()=>void restore(0)}>{t('Restore')}</Button></Stack></Paper>}{versions?.length===0&&<Alert severity="info">{t('No uploaded versions yet.')}</Alert>}{versions?.map(version=><Paper variant="outlined" sx={{p:2}} key={version.version_number}><Stack direction={{xs:'column',sm:'row'}} justifyContent="space-between" gap={2}><Box><Stack direction="row" gap={1} alignItems="center"><Typography fontWeight={700}>{t('Version {{version}}',{version:version.version_number})}</Typography>{version.active&&<Chip size="small" color="success" label={t('Active')}/>}</Stack><Typography color="text.secondary">{version.created_by} · {new Date(version.created_at).toLocaleString()}</Typography><Typography variant="caption">{version.definition_hash}</Typography></Box><Button startIcon={<RotateCcw size={17}/>} disabled={busy||version.active} onClick={()=>void restore(version.version_number)}>{t('Restore')}</Button></Stack></Paper>)}</Stack></DialogContent><DialogActions><Button onClick={()=>setVersions(null)}>{t('Close')}</Button></DialogActions></Dialog>
  </Stack>;
}
