<?php
declare(strict_types=1);
// Reuse the isolated booking fixture and its SQL acceptance before applying migration 036.
$_ENV['CLIENT_FORMS_ENABLED']='false';
require __DIR__.'/recurring-bookings.php';
use Wellness\Auth\AuthContext;
use Wellness\Http\ApiException;
use Wellness\Service\{AuditLogger,ClientFormsService,ClientService,RecurrencePattern};
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/005_customer_onboarding.sql'));
$pdo->exec("INSERT INTO form_templates(clinic_id,owner_practitioner_id,name,form_type,definition) VALUES(1,3,'Legacy synthetic template','intake','{}')");
$legacy=(int)$pdo->lastInsertId();
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/036_client_intake_forms.sql'));
$_ENV['CLIENT_FORMS_ENABLED']='true';$forms=new ClientFormsService($database,new AuditLogger($database));$checks=0;
$assert=function(bool $ok,string $message)use(&$checks){if(!$ok)throw new RuntimeException($message);$checks++;};
$denies=function(callable $action,string $code)use($assert){try{$action();}catch(ApiException $e){$assert($e->errorCode===$code,'Expected '.$code.', got '.$e->errorCode);return;}throw new RuntimeException('Expected '.$code);};
$assert($pdo->query('SELECT family_key FROM form_templates WHERE id='.$legacy)->fetchColumn()===null,'Legacy template must remain unchanged');
$clinician=new AuthContext(2,1,'','','','staff',['practitioner']);$reception=new AuthContext(1,1,'','','','staff',['reception']);
$pdo->exec("INSERT INTO users(id,clinic_id,email,display_name,user_type,status) VALUES(11,1,'other-practitioner@example.test','Other practitioner','staff','active'); INSERT INTO practitioners(id,user_id,discipline,booking_mode) VALUES(12,11,'Massage','practitioner_managed')");
$other=new AuthContext(11,1,'','','','staff',['practitioner']);
$definition=['instructions'=>'Synthetic test only','questions'=>[['id'=>'text','label'=>'Test text','label_fr'=>'Texte fictif','type'=>'text','required'=>true],['id'=>'yes','label'=>'Test yes/no','type'=>'yes_no','required'=>true],['id'=>'consent','label'=>'Test acknowledgement','type'=>'consent','required'=>true]]];
$publish=['owner_practitioner_id'=>3,'name'=>'Synthetic intake','form_type'=>'consent','definition'=>$definition,'service_ids'=>[4],'idempotency_key'=>'synthetic-form-publish-one'];
$first=$forms->publish($clinician,$publish,'forms-test');$assert($first['version']===1,'First version');$assert($forms->publish($clinician,$publish,'forms-test')===$first,'Publication replay');
$denies(fn()=>$forms->publish($reception,$publish,'forms-test'),'forbidden');
$denies(fn()=>$forms->publish($client,$publish,'forms-test'),'forbidden');
$denies(fn()=>$forms->publish($other,array_replace($publish,['idempotency_key'=>'other-practitioner-publication']),'forms-test'),'forbidden');
$assignment=['template_id'=>$first['id'],'idempotency_key'=>'synthetic-form-assignment-one'];
$task=$forms->assign($clinician,8,$assignment,'forms-test');$assert($forms->assign($clinician,8,$assignment,'forms-test')===$task,'Assignment replay');
$assert(count($forms->list($client,8,[],'forms-test')['items'])===1,'Own form list');
$assert(!$forms->list($admin,8,[],'forms-test')['items'][0]['can_read_answers'],'Admin metadata must exclude clinical answers');
$denies(fn()=>$forms->detail($admin,$task['id'],'forms-test'),'forbidden');
$denies(fn()=>$forms->detail(new AuthContext(9,1,'','','','client',[]),$task['id'],'forms-test'),'form_not_found');
$denies(fn()=>$forms->detail(new AuthContext(10,2,'','','','client',[]),$task['id'],'forms-test'),'form_not_found');
$denies(fn()=>$forms->detail($other,$task['id'],'forms-test'),'form_not_found');
$next=array_replace($publish,['name'=>'Synthetic intake revised','expected_version'=>1,'idempotency_key'=>'synthetic-form-publish-two']);$next['definition']['questions'][0]['label']='Revised text';
$second=$forms->publish($clinician,$next,'forms-test',$first['id']);$assert($second['version']===2,'Second version');
$assert($forms->detail($client,$task['id'],'forms-test')['definition']['questions'][0]['label']==='Test text','Assigned questions are pinned');
$assert(count($forms->history($clinician,$second['id'])['items'])===2,'Version history');
$assert($forms->assign($clinician,8,$assignment,'forms-test')===$task,'Assignment replay survives new template publication');
$denies(fn()=>$forms->publish($clinician,array_replace($next,['idempotency_key'=>'stale-form-publication']),'forms-test',$first['id']),'form_changed');
$denies(fn()=>$forms->assign($clinician,8,array_replace($assignment,['idempotency_key'=>'old-template-assignment']),'forms-test'),'form_changed');
$answers=['text'=>'Synthetic only','yes'=>false,'consent'=>true];
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>[],'confirmed'=>true],'forms-test'),'invalid_form');
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>false],'forms-test'),'form_changed');
$result=$forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test');
$assert($result['status']==='submitted','Submission');$assert($forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test')===$result,'Submission retry');
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>array_replace($answers,['text'=>'Different']),'confirmed'=>true],'forms-test'),'form_already_submitted');
$assert((int)$pdo->query('SELECT COUNT(*) FROM form_submissions')->fetchColumn()===1,'No duplicate submissions');
$assert((int)$pdo->query('SELECT COUNT(*) FROM consent_records')->fetchColumn()===1,'No duplicate consent evidence');
$denies(fn()=>$forms->transition($admin,$task['id'],['action'=>'review','version'=>2],'forms-test'),'forbidden');
$forms->transition($clinician,$task['id'],['action'=>'review','version'=>2],'forms-test');$assert($forms->detail($client,$task['id'],'forms-test')['status']==='reviewed','Review visible to client');
$pending=$forms->assign($admin,8,['template_id'=>$second['id'],'idempotency_key'=>'pending-form-revocation'],'forms-test');$forms->transition($reception,$pending['id'],['action'=>'revoke','version'=>1],'forms-test');
$denies(fn()=>$forms->submit($client,$pending['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test'),'form_changed');
// Booking previews must not leave assigned forms; series commit creates one per visit.
$create=array_replace($body,['starts_at'=>(new DateTimeImmutable($start))->modify('+140 days')->format('Y-m-d\TH:i:sP'),'idempotency_key'=>'forms-recurring-create']);
$before=(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn();$preview=$series->create($client,$create,'forms-test',false);
$assert($preview['ready']&&(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn()===$before,'Preview rolls back assigned tasks');
$created=$series->create($client,$create+['preview_token'=>$preview['preview_token']],'forms-test',true);$assert($created['applied']&&(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn()===$before+3,'Service rules assign each occurrence');
$ids=array_column($created['items'],'appointment_id');$bookings->update($client,$ids[0],['action'=>'cancel','version'=>1,'expected_cancellation_fee_cents'=>0],'forms-test');
$assert($pdo->query('SELECT status FROM client_form_tasks WHERE appointment_id='.$ids[0])->fetchColumn()==='revoked','Cancellation revokes pending automatic form');
$assert((int)$pdo->query("SELECT COUNT(*) FROM client_form_tasks WHERE status='pending' AND appointment_id IN(".implode(',',$ids).')')->fetchColumn()===2,'Other occurrences untouched');
// Existing supervised client merge must move both tasks and immutable responses.
$otherTemplate=$forms->publish($other,array_replace($publish,['owner_practitioner_id'=>12,'service_ids'=>[],'idempotency_key'=>'other-clinician-owned-form']),'forms-test');
$denies(fn()=>$forms->assign($other,8,['template_id'=>$otherTemplate['id'],'idempotency_key'=>'unrelated-client-assignment'],'forms-test'),'client_not_found');
$forms->assign($admin,8,['template_id'=>$otherTemplate['id'],'idempotency_key'=>'admin-approved-clinician-assignment'],'forms-test');
$clients=new ClientService($database,new AuditLogger($database));$assert((int)$clients->practitionerList($other,[])['items'][0]['id']===8,'Explicit assignment appears in practitioner directory');
$_ENV['CLIENT_FORMS_ENABLED']='false';
$mergePreview=$clients->mergePreview($admin,9,8,'forms-test');$merge=$clients->merge($admin,9,8,['survivor_revision'=>$mergePreview['survivor']['revision'],'duplicate_revision'=>$mergePreview['duplicate']['revision'],'reason'=>'Synthetic fixture consolidation','confirmation'=>'MERGE 8 INTO 9'],'forms-test');
$_ENV['CLIENT_FORMS_ENABLED']='true';
$assert((int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks WHERE client_id=8')->fetchColumn()===0,'Merge moves tasks');
$denies(fn()=>$forms->detail($client,$task['id'],'forms-test'),'form_not_found');
$assert($forms->detail(new AuthContext(9,1,'','','','client',[]),$task['id'],'forms-test')['answers']['text']==='Synthetic only','Merged client owns preserved answers');
$metadata=$pdo->query("SELECT metadata FROM audit_logs WHERE action LIKE 'form.%'")->fetchAll(PDO::FETCH_COLUMN);$assert(!str_contains(json_encode($metadata),'Synthetic only'),'Audit metadata excludes answers');
$_ENV['CLIENT_FORMS_ENABLED']='false';$denies(fn()=>$forms->list($client,8,[],'forms-test'),'forms_disabled');
$assert(!$pdo->inTransaction(),'No leaked transaction');
echo "Client forms real SQL acceptance: $checks checks passed on ".$pdo->getAttribute(PDO::ATTR_SERVER_VERSION).".\n";
