<?php
declare(strict_types=1);
// Reuse the isolated booking fixture and its SQL acceptance before applying migration 036.
$_ENV['CLIENT_FORMS_ENABLED']='false';
require __DIR__.'/recurring-bookings.php';
use Wellness\Auth\AuthContext;
use Wellness\Http\ApiException;
use Wellness\Service\{AuditLogger,ClientFormsService,ClientService,RecurrencePattern};
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/005_customer_onboarding.sql'));
$pdo->exec("INSERT INTO form_templates(clinic_id,owner_practitioner_id,name,form_type,definition) VALUES(1,3,'Legacy synthetic template','intake','{}')");
$legacy=(int)$pdo->lastInsertId();
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/036_client_intake_forms.sql'));
$_ENV['CLIENT_FORMS_ENABLED']='true';$forms=new ClientFormsService($database,new AuditLogger($database));$checks=0;
$assert=function(bool $ok,string $message)use(&$checks){if(!$ok)throw new RuntimeException($message);$checks++;};
$denies=function(callable $action,string $code)use($assert){try{$action();}catch(ApiException $e){$assert($e->errorCode===$code,'Expected '.$code.', got '.$e->errorCode);return;}throw new RuntimeException('Expected '.$code);};
$assert($pdo->query('SELECT family_key FROM form_templates WHERE id='.$legacy)->fetchColumn()===null,'Legacy template must remain unchanged');
$clinician=new AuthContext(2,1,'','','','staff',['practitioner']);$reception=new AuthContext(1,1,'','','','staff',['reception']);
$pdo->exec("INSERT INTO users(id,clinic_id,email,display_name,user_type,status) VALUES(11,1,'other-practitioner@example.test','Other practitioner','staff','active'); INSERT INTO practitioners(id,user_id,discipline,booking_mode) VALUES(12,11,'Massage','practitioner_managed')");
$other=new AuthContext(11,1,'','','','staff',['practitioner']);
$definition=['instructions'=>'Synthetic test only','questions'=>[['id'=>'text','label'=>'Test text','label_fr'=>'Texte fictif','type'=>'text','required'=>true],['id'=>'yes','label'=>'Test yes/no','type'=>'yes_no','required'=>true],['id'=>'consent','label'=>'Test acknowledgement','type'=>'consent','required'=>true]]];
$publish=['owner_practitioner_id'=>3,'name'=>'Synthetic intake','form_type'=>'consent','definition'=>$definition,'service_ids'=>[4],'idempotency_key'=>'synthetic-form-publish-one'];
$first=$forms->publish($clinician,$publish,'forms-test');$assert($first['version']===1,'First version');$assert($forms->publish($clinician,$publish,'forms-test')===$first,'Publication replay');
$denies(fn()=>$forms->publish($reception,$publish,'forms-test'),'forbidden');
$denies(fn()=>$forms->publish($client,$publish,'forms-test'),'forbidden');
$denies(fn()=>$forms->publish($other,array_replace($publish,['idempotency_key'=>'other-practitioner-publication']),'forms-test'),'forbidden');
$assignment=['template_id'=>$first['id'],'idempotency_key'=>'synthetic-form-assignment-one'];
$task=$forms->assign($clinician,8,$assignment,'forms-test');$assert($forms->assign($clinician,8,$assignment,'forms-test')===$task,'Assignment replay');
$assert(count($forms->list($client,8,[],'forms-test')['items'])===1,'Own form list');
$assert(!$forms->list($admin,8,[],'forms-test')['items'][0]['can_read_answers'],'Admin metadata must exclude clinical answers');
$denies(fn()=>$forms->detail($admin,$task['id'],'forms-test'),'forbidden');
$denies(fn()=>$forms->detail(new AuthContext(9,1,'','','','client',[]),$task['id'],'forms-test'),'form_not_found');
$denies(fn()=>$forms->detail(new AuthContext(10,2,'','','','client',[]),$task['id'],'forms-test'),'form_not_found');
$denies(fn()=>$forms->detail($other,$task['id'],'forms-test'),'form_not_found');
$next=array_replace($publish,['name'=>'Synthetic intake revised','expected_version'=>1,'idempotency_key'=>'synthetic-form-publish-two']);$next['definition']['questions'][0]['label']='Revised text';
$second=$forms->publish($clinician,$next,'forms-test',$first['id']);$assert($second['version']===2,'Second version');
$assert($forms->detail($client,$task['id'],'forms-test')['definition']['questions'][0]['label']==='Test text','Assigned questions are pinned');
$assert(count($forms->history($clinician,$second['id'])['items'])===2,'Version history');
$assert($forms->assign($clinician,8,$assignment,'forms-test')===$task,'Assignment replay survives new template publication');
$denies(fn()=>$forms->publish($clinician,array_replace($next,['idempotency_key'=>'stale-form-publication']),'forms-test',$first['id']),'form_changed');
$denies(fn()=>$forms->assign($clinician,8,array_replace($assignment,['idempotency_key'=>'old-template-assignment']),'forms-test'),'form_changed');
$answers=['text'=>'Synthetic only','yes'=>false,'consent'=>true];
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>[],'confirmed'=>true],'forms-test'),'invalid_form');
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>false],'forms-test'),'form_changed');
$result=$forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test');
$assert($result['status']==='submitted','Submission');$assert($forms->submit($client,$task['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test')===$result,'Submission retry');
$denies(fn()=>$forms->submit($client,$task['id'],['version'=>1,'answers'=>array_replace($answers,['text'=>'Different']),'confirmed'=>true],'forms-test'),'form_already_submitted');
$assert((int)$pdo->query('SELECT COUNT(*) FROM form_submissions')->fetchColumn()===1,'No duplicate submissions');
$assert((int)$pdo->query('SELECT COUNT(*) FROM consent_records')->fetchColumn()===1,'No duplicate consent evidence');
$denies(fn()=>$forms->transition($admin,$task['id'],['action'=>'review','version'=>2],'forms-test'),'forbidden');
$forms->transition($clinician,$task['id'],['action'=>'review','version'=>2],'forms-test');$assert($forms->detail($client,$task['id'],'forms-test')['status']==='reviewed','Review visible to client');
$pending=$forms->assign($admin,8,['template_id'=>$second['id'],'idempotency_key'=>'pending-form-revocation'],'forms-test');$forms->transition($reception,$pending['id'],['action'=>'revoke','version'=>1],'forms-test');
$denies(fn()=>$forms->submit($client,$pending['id'],['version'=>1,'answers'=>$answers,'confirmed'=>true],'forms-test'),'form_changed');
// Booking previews must not leave assigned forms; series commit creates one per visit.
$create=array_replace($body,['starts_at'=>(new DateTimeImmutable($start))->modify('+140 days')->format('Y-m-d\TH:i:sP'),'idempotency_key'=>'forms-recurring-create']);
$before=(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn();$preview=$series->create($client,$create,'forms-test',false);
$assert($preview['ready']&&(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn()===$before,'Preview rolls back assigned tasks');
$created=$series->create($client,$create+['preview_token'=>$preview['preview_token']],'forms-test',true);$assert($created['applied']&&(int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks')->fetchColumn()===$before+3,'Service rules assign each occurrence');
$ids=array_column($created['items'],'appointment_id');$bookings->update($client,$ids[0],['action'=>'cancel','version'=>1,'expected_cancellation_fee_cents'=>0],'forms-test');
$assert($pdo->query('SELECT status FROM client_form_tasks WHERE appointment_id='.$ids[0])->fetchColumn()==='revoked','Cancellation revokes pending automatic form');
$assert((int)$pdo->query("SELECT COUNT(*) FROM client_form_tasks WHERE status='pending' AND appointment_id IN(".implode(',',$ids).')')->fetchColumn()===2,'Other occurrences untouched');
// New answer types append a version; existing text responses stay pinned.
$typedPublish=array_replace($next,['expected_version'=>2,'idempotency_key'=>'typed-form-publish-three','service_ids'=>[]]);
$typedPublish['definition']['questions'][0]['type']='date';$typedPublish['definition']['questions'][0]['no_future']=true;
$typedPublish['definition']['questions'][]=['id'=>'phone','label'=>'Synthetic phone','type'=>'phone','required'=>true];
$typedPublish['definition']['questions'][]=['id'=>'email','label'=>'Synthetic email','type'=>'email','required'=>true];
$typedPublish['definition']['sections']=[['id'=>'info','title'=>'Client Information','description'=>'Synthetic section instructions'],['id'=>'health','title'=>'Health History','title_fr'=>'Antécédents médicaux','description_fr'=>'Consignes fictives']];
$typedPublish['definition']['questions'][0]['section_id']='info';
$typedPublish['definition']['questions'][1]['section_id']='health';
$third=$forms->publish($clinician,$typedPublish,'forms-test',$second['id']);
$typedTask=$forms->assign($clinician,8,['template_id'=>$third['id'],'idempotency_key'=>'typed-form-assignment'],'forms-test');
$typedAnswers=['text'=>'2000-02-29','yes'=>false,'consent'=>true,'phone'=>'+14165551234','email'=>'test@example.test'];
$typedBody=['version'=>1,'confirmed'=>true,'answers'=>$typedAnswers];
$denies(fn()=>$forms->submit($client,$typedTask['id'],array_replace($typedBody,['answers'=>array_replace($typedAnswers,['text'=>'2001-02-29'])]),'forms-test'),'invalid_form');
$denies(fn()=>$forms->submit($client,$typedTask['id'],array_replace($typedBody,['answers'=>array_replace($typedAnswers,['phone'=>'4165551234'])]),'forms-test'),'invalid_form');
$denies(fn()=>$forms->submit($client,$typedTask['id'],array_replace($typedBody,['answers'=>array_replace($typedAnswers,['email'=>'bad@'])]),'forms-test'),'invalid_form');
$typedSubmitted=$forms->submit($client,$typedTask['id'],$typedBody,'forms-test');
$assert($forms->submit($client,$typedTask['id'],$typedBody,'forms-test')===$typedSubmitted,'Typed submission replay');
$assert($forms->detail($clinician,$typedTask['id'],'forms-test')['answers']['phone']==='+14165551234','Canonical phone stored');
$assert($forms->detail($client,$task['id'],'forms-test')['definition']['questions'][0]['type']==='text','Old assignment retains text type');
$assert($forms->detail($client,$task['id'],'forms-test')['answers']['text']==='Synthetic only','Old text response survives new date type');
$sectionDetail=$forms->detail($client,$typedTask['id'],'forms-test');
$assert(array_column($sectionDetail['definition']['sections'],'title')===['Client Information','Health History'],'Stored section order');
$assert($sectionDetail['definition']['sections'][0]['description']==='Synthetic section instructions','Stored section description');
$fourthBody=array_replace($typedPublish,['expected_version'=>3,'idempotency_key'=>'section-form-publish-four']);
$fourthBody['definition']['sections'][0]['title']='Revised information';$fourthBody['definition']['sections'][0]['description']='Revised instructions';
$fourth=$forms->publish($clinician,$fourthBody,'forms-test',$third['id']);
$assert($forms->detail($client,$typedTask['id'],'forms-test')['definition']['sections'][0]['title']==='Client Information','Assigned section title pinned');
$assert($forms->detail($client,$typedTask['id'],'forms-test')['definition']['sections'][0]['description']==='Synthetic section instructions','Assigned section description pinned');
$assert($forms->history($clinician,$fourth['id'])['items'][0]['definition']['sections'][0]['title']==='Revised information','Section changes append a version');
$choiceBody=array_replace($fourthBody,['expected_version'=>4,'idempotency_key'=>'choice-form-publish-five']);
$choiceOptions=[['id'=>'low','label'=>'Low'],['id'=>'moderate','label'=>'Moderate'],['id'=>'high','label'=>'High']];
$choiceBody['definition']['questions'][0]['type']='single_choice';unset($choiceBody['definition']['questions'][0]['no_future']);
$choiceBody['definition']['questions'][0]['options']=$choiceOptions;
$choiceBody['definition']['questions'][]=['id'=>'habits','label'=>'Synthetic habits','type'=>'multiple_choice','required'=>true,'options'=>$choiceOptions];
$fifth=$forms->publish($clinician,$choiceBody,'forms-test',$fourth['id']);
$choiceTask=$forms->assign($clinician,8,['template_id'=>$fifth['id'],'idempotency_key'=>'choice-form-assignment'],'forms-test');
$choiceAnswers=array_replace($typedAnswers,['text'=>'moderate','habits'=>['low','high']]);
$choiceSubmit=['version'=>1,'confirmed'=>true,'answers'=>$choiceAnswers];
$denies(fn()=>$forms->submit($client,$choiceTask['id'],array_replace($choiceSubmit,['answers'=>array_replace($choiceAnswers,['habits'=>[]])]),'forms-test'),'invalid_form');
$denies(fn()=>$forms->submit($client,$choiceTask['id'],array_replace($choiceSubmit,['answers'=>array_replace($choiceAnswers,['text'=>'unknown'])]),'forms-test'),'invalid_form');
$choiceResult=$forms->submit($client,$choiceTask['id'],$choiceSubmit,'forms-test');
$reordered=$choiceSubmit;$reordered['answers']['habits']=['high','low'];
$assert($forms->submit($client,$choiceTask['id'],$reordered,'forms-test')===$choiceResult,'Checkbox order does not duplicate submission');
$assert($forms->detail($clinician,$choiceTask['id'],'forms-test')['answers']['habits']===['high','low'],'Multiple choices stored canonically');
$sixthBody=array_replace($choiceBody,['expected_version'=>5,'idempotency_key'=>'choice-form-publish-six']);$sixthBody['definition']['questions'][0]['options'][2]['label']='Very high';
$forms->publish($clinician,$sixthBody,'forms-test',$fifth['id']);
$assert($forms->detail($client,$choiceTask['id'],'forms-test')['definition']['questions'][0]['options'][2]['label']==='High','Original option labels pinned');
$assert($forms->detail($client,$typedTask['id'],'forms-test')['definition']['questions'][0]['type']==='date','Original date type pinned after choice update');
// Author drafts: private, versioned and idempotent, with an independent rollout gate.
$drafts=new \Wellness\Service\ClientFormDraftsService($database,new AuditLogger($database));
$_ENV['FORM_TEMPLATE_DRAFTS_ENABLED']='false';
$assert($forms->templates($clinician,[])['drafts_enabled']===false,'Existing forms list does not query the draft table before migration');
$denies(fn()=>$drafts->list($clinician,[]),'form_drafts_disabled');
$doc=['format'=>'wellness-form','format_version'=>1,'name'=>'Source example','form_type'=>'intake','definition'=>$definition];
$assert($drafts->validate($clinician,['document'=>$doc])['name']==='Source example','Source validation works without draft storage');
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/037_form_template_drafts.sql'));
$_ENV['FORM_TEMPLATE_DRAFTS_ENABLED']='true';
$unfinished=['owner_practitioner_id'=>3,'name'=>'','form_type'=>'consent','definition'=>['questions'=>[['id'=>'q1','label'=>'','type'=>'text','required'=>true]]],'service_ids'=>[],'idempotency_key'=>'draft-create-synthetic'];
$count=(int)$pdo->query('SELECT COUNT(*) FROM form_templates')->fetchColumn();
$d=$drafts->save($clinician,$unfinished,'forms-test');
$assert($drafts->save($clinician,$unfinished,'forms-test')===$d,'Create draft retry returns the same draft');
$assert((int)$pdo->query('SELECT COUNT(*) FROM form_templates')->fetchColumn()===$count,'Draft does not create an assignable template');
$assert(count($drafts->list($clinician,[])['items'])===1,'Owner sees saved draft');
$assert(count($drafts->list($admin,[])['items'])===0,'Administrator cannot browse another author draft');
$assert($drafts->detail($clinician,$d['id'],'forms-test')['payload']['definition']['questions'][0]['label']==='','Incomplete labels survive reload');
$denies(fn()=>$drafts->detail($other,$d['id'],'forms-test'),'draft_not_found');
$denies(fn()=>$drafts->detail($admin,$d['id'],'forms-test'),'draft_not_found');
$denies(fn()=>$drafts->detail(new AuthContext(2,2,'','','','staff',['clinic_admin']),$d['id'],'forms-test'),'draft_not_found');
$denies(fn()=>$drafts->save($reception,$unfinished,'forms-test'),'forbidden');
$denies(fn()=>$drafts->list($client,[]),'forbidden');
$denies(fn()=>$drafts->validate($reception,['document'=>$doc]),'forbidden');
$denies(fn()=>$drafts->save($other,array_replace($unfinished,['idempotency_key'=>'draft-other-owner-key']),'forms-test'),'forbidden');
$denies(fn()=>$drafts->save($clinician,array_replace($unfinished,['name'=>'Changed request']),'forms-test'),'idempotency_conflict');
$updated=array_replace($unfinished,['name'=>'Saved draft','form_type'=>'intake','definition'=>$definition,'draft_version'=>1,'idempotency_key'=>'draft-update-synthetic']);
$d2=$drafts->save($clinician,$updated,'forms-test',$d['id']);$assert($d2['version']===2,'Update draft increments revision');
$assert($drafts->save($clinician,$updated,'forms-test',$d['id'])===$d2,'Update draft replay');
$denies(fn()=>$drafts->save($clinician,array_replace($updated,['idempotency_key'=>'draft-stale-key']),'forms-test',$d['id']),'draft_changed');
$assert($drafts->detail($clinician,$d['id'],'forms-test')['payload']['name']==='Saved draft','Stale update leaves stored draft intact');
foreach([array_replace($doc,['answers'=>['private']]),array_replace($doc,['owner_practitioner_id'=>12]),array_replace($doc,['format_version'=>2]),array_replace($doc,['form_type'=>'unknown'])] as $bad)$denies(fn()=>$drafts->import($clinician,['document'=>$bad,'owner_practitioner_id'=>3,'idempotency_key'=>'bad-import-key'],'forms-test'),'invalid_form');
$import=['document'=>$doc,'owner_practitioner_id'=>3,'idempotency_key'=>'draft-import-synthetic'];
$imported=$drafts->import($clinician,$import,'forms-test');$assert($drafts->import($clinician,$import,'forms-test')===$imported,'Import replay does not duplicate draft');
$importDetail=$drafts->detail($clinician,$imported['id'],'forms-test')['payload'];$assert($importDetail['service_ids']===[]&&$importDetail['previous_template_id']===null,'Import creates an unbound private draft');
$denies(fn()=>$drafts->import($clinician,array_replace($import,['owner_practitioner_id'=>12,'idempotency_key'=>'unauthorized-import']),'forms-test'),'forbidden');
$draftPublish=array_replace($updated,['idempotency_key'=>'draft-publish-synthetic','draft_id'=>$d['id'],'draft_version'=>2]);
$denies(fn()=>$forms->publish($clinician,array_replace($draftPublish,['name'=>'']),'forms-test'),'invalid_form');
$assert($drafts->detail($clinician,$d['id'],'forms-test')['status']==='draft','Invalid publication leaves draft editable');
$denies(fn()=>$forms->publish($clinician,array_replace($draftPublish,['draft_version'=>1]),'forms-test'),'draft_changed');
$denies(fn()=>$forms->publish($admin,$draftPublish,'forms-test'),'draft_not_found');
$publishedDraft=$forms->publish($clinician,$draftPublish,'forms-test');
$assert($forms->publish($clinician,$draftPublish,'forms-test')===$publishedDraft,'Publication retry survives draft state transition');
$assert($drafts->detail($clinician,$d['id'],'forms-test')['status']==='published','Draft closes atomically on publication');
$assert(count($drafts->list($clinician,[])['items'])===1,'Published draft removed from resume list');
$denies(fn()=>$drafts->save($clinician,$updated,'forms-test',$d['id']),'draft_changed');
$denies(fn()=>$forms->publish($clinician,array_replace($draftPublish,['idempotency_key'=>'draft-republish-key']),'forms-test'),'draft_changed');
// Some hosted PDO drivers return numeric columns as strings. API versions must remain JSON numbers.
$originalStringify=$pdo->getAttribute(PDO::ATTR_STRINGIFY_FETCHES);
$pdo->setAttribute(PDO::ATTR_STRINGIFY_FETCHES,true);
try {
    $listed=array_values(array_filter($forms->templates($clinician,[])['items'],fn($row)=>(int)$row['id']===$publishedDraft['id']))[0];
    $assert($listed['version']===1,'Template list returns integer versions with stringifying PDO');
    $assert($forms->history($clinician,$publishedDraft['id'])['items'][0]['version']===1,'History returns integer versions with stringifying PDO');
    $savedFromList=$drafts->save($clinician,array_replace($updated,['previous_template_id'=>$publishedDraft['id'],'expected_version'=>$listed['version'],'idempotency_key'=>'stringified-version-draft']),'forms-test');
    $assert($savedFromList['status']==='draft','Draft of a listed template saves with stringifying PDO');
} finally { $pdo->setAttribute(PDO::ATTR_STRINGIFY_FETCHES,$originalStringify); }
$versionDraft=array_replace($updated,['previous_template_id'=>$publishedDraft['id'],'expected_version'=>1,'idempotency_key'=>'version-draft-create']);unset($versionDraft['draft_version']);
$vd=$drafts->save($clinician,$versionDraft,'forms-test');
$vp=array_replace($versionDraft,['name'=>'Source revised','draft_id'=>$vd['id'],'draft_version'=>1,'idempotency_key'=>'version-draft-publish']);
$denies(fn()=>$forms->publish($clinician,$vp,'forms-test'),'draft_changed');
$vpub=$forms->publish($clinician,$vp,'forms-test',$publishedDraft['id']);
$assert($vpub['version']===2,'Resumed source changes append a published version');
$assert($forms->history($clinician,$vpub['id'])['items'][1]['name']==='Saved draft','Published original remains immutable');
$assert(!$pdo->inTransaction(),'Draft paths do not leak transactions');
// Existing supervised client merge must move both tasks and immutable responses.
$otherTemplate=$forms->publish($other,array_replace($publish,['owner_practitioner_id'=>12,'service_ids'=>[],'idempotency_key'=>'other-clinician-owned-form']),'forms-test');
$denies(fn()=>$forms->assign($other,8,['template_id'=>$otherTemplate['id'],'idempotency_key'=>'unrelated-client-assignment'],'forms-test'),'client_not_found');
$forms->assign($admin,8,['template_id'=>$otherTemplate['id'],'idempotency_key'=>'admin-approved-clinician-assignment'],'forms-test');
$clients=new ClientService($database,new AuditLogger($database));$assert((int)$clients->practitionerList($other,[])['items'][0]['id']===8,'Explicit assignment appears in practitioner directory');
$_ENV['CLIENT_FORMS_ENABLED']='false';
$mergePreview=$clients->mergePreview($admin,9,8,'forms-test');$merge=$clients->merge($admin,9,8,['survivor_revision'=>$mergePreview['survivor']['revision'],'duplicate_revision'=>$mergePreview['duplicate']['revision'],'reason'=>'Synthetic fixture consolidation','confirmation'=>'MERGE 8 INTO 9'],'forms-test');
$_ENV['CLIENT_FORMS_ENABLED']='true';
$assert((int)$pdo->query('SELECT COUNT(*) FROM client_form_tasks WHERE client_id=8')->fetchColumn()===0,'Merge moves tasks');
$denies(fn()=>$forms->detail($client,$task['id'],'forms-test'),'form_not_found');
$assert($forms->detail(new AuthContext(9,1,'','','','client',[]),$task['id'],'forms-test')['answers']['text']==='Synthetic only','Merged client owns preserved answers');
$metadata=$pdo->query("SELECT metadata FROM audit_logs WHERE action LIKE 'form.%'")->fetchAll(PDO::FETCH_COLUMN);$assert(!str_contains(json_encode($metadata),'Synthetic only'),'Audit metadata excludes answers');
// Reproduce a legacy result charset returning valid stored JSON as invalid UTF-8.
$unicodeText="Client\u{2019}s stress: \u{00E9} \u{4E2D} \u{1F600}";
$unicodeDefinition=\Wellness\Service\ClientFormDefinition::definition(['instructions'=>$unicodeText,'questions'=>[['id'=>'text','label'=>$unicodeText,'type'=>'text','required'=>true]]],'intake');
$unicodeTemplate=$forms->publish($clinician,['owner_practitioner_id'=>3,'name'=>'UTF8 fixture','form_type'=>'intake','definition'=>$unicodeDefinition,'service_ids'=>[],'idempotency_key'=>'utf8-form-fixture-publish'],'forms-test');
$unicodeJson=json_encode($unicodeDefinition,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR);
$pdo->prepare('UPDATE form_templates SET definition=? WHERE id=?')->execute([$unicodeJson,$unicodeTemplate['id']]);
$mergedClient=new AuthContext(9,1,'','','','client',[]);
$unicodeTask=$forms->assign($clinician,9,['template_id'=>$unicodeTemplate['id'],'idempotency_key'=>'utf8-task-fixture-key'],'forms-test');
$unicodeSubmit=['version'=>1,'confirmed'=>true,'answers'=>['text'=>$unicodeText]];
$forms->submit($mergedClient,$unicodeTask['id'],$unicodeSubmit,'forms-test');
$pdo->prepare('UPDATE form_submissions SET response_data=? WHERE id=(SELECT submission_id FROM client_form_tasks WHERE id=?)')->execute([json_encode(['text'=>$unicodeText],JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),$unicodeTask['id']]);
$beforeHex=$pdo->query('SELECT HEX(definition) FROM form_templates WHERE id='.$unicodeTemplate['id'])->fetchColumn();
$pdo->exec("SET character_set_results=latin1");
try{
    $assert((int)$pdo->query('SELECT JSON_VALID(definition) FROM form_templates WHERE id='.$unicodeTemplate['id'])->fetchColumn()===1,'Stored Unicode JSON is valid in the database');
    $raw=$pdo->query('SELECT definition FROM form_templates WHERE id='.$unicodeTemplate['id'])->fetchColumn();
    try{json_decode($raw,true,32,JSON_THROW_ON_ERROR);throw new RuntimeException('Expected baseline UTF-8 transport failure');}catch(JsonException $e){$assert($e->getCode()===JSON_ERROR_UTF8,'Baseline reproduces the hosted JSON error code 5');}
    $templates=$forms->templates($clinician,[])['items'];$unicodeRow=array_values(array_filter($templates,fn($row)=>(int)$row['id']===$unicodeTemplate['id']))[0];
    $assert($unicodeRow['definition']===$unicodeDefinition,'Template list preserves Unicode despite the result charset');
    $assert(is_string(json_encode($templates,JSON_THROW_ON_ERROR)),'Template response is valid UTF-8 JSON');
    $assert($forms->history($clinician,$unicodeTemplate['id'])['items'][0]['definition']===$unicodeDefinition,'History preserves original Unicode');
    $detail=$forms->detail($mergedClient,$unicodeTask['id'],'forms-test');
    $assert($detail['definition']===$unicodeDefinition,'Assigned definition preserves Unicode');
    $assert($detail['answers']['text']===$unicodeText,'Submitted answers preserve Unicode');
    $assert($forms->submit($mergedClient,$unicodeTask['id'],$unicodeSubmit,'forms-test')['status']==='submitted','Unicode answer retry remains idempotent');
    $assert($pdo->query('SELECT HEX(definition) FROM form_templates WHERE id='.$unicodeTemplate['id'])->fetchColumn()===$beforeHex,'Read path does not rewrite the stored form');
}finally{$pdo->exec("SET character_set_results=utf8mb4");}
$_ENV['CLIENT_FORMS_ENABLED']='false';$denies(fn()=>$forms->list($client,8,[],'forms-test'),'forms_disabled');
$assert(!$pdo->inTransaction(),'No leaked transaction');
echo "Client forms real SQL acceptance: $checks checks passed on ".$pdo->getAttribute(PDO::ATTR_SERVER_VERSION).".\n";
