<?php
declare(strict_types=1);
// Synthetic localhost database only. No .env or hosted credentials are loaded.
require dirname(__DIR__,2).'/vendor/autoload.php';
use Wellness\Auth\AuthContext;
use Wellness\Auth\StaffMembershipResolver;
use Wellness\Auth\VerifiedIdentity;
use Wellness\Auth\EntraAuthenticator;
use Firebase\JWT\JWT;
use Wellness\ClinicContext;
use Wellness\Config;
use Wellness\Database;
use Wellness\Http\ApiException;
use Wellness\Http\Request;
use Wellness\Service\AdminService;
use Wellness\Service\AuditLogger;
use Wellness\Service\CatalogService;
use Wellness\Service\ClinicManagementService;
use Wellness\Service\ClinicPortalUrl;
use Wellness\Service\CustomerOnboarding;
use Wellness\Service\ClientService;

if (getenv('CLINIC_TEST_ALLOW_CREATE')!=='true') throw new RuntimeException('Set CLINIC_TEST_ALLOW_CREATE=true for the synthetic localhost rehearsal.');
$port=(int)(getenv('CLINIC_TEST_PORT')?:13319);
$pdo=new PDO("mysql:host=127.0.0.1;port=$port;charset=utf8mb4",getenv('CLINIC_TEST_USER')?:'root',getenv('CLINIC_TEST_PASSWORD')?:'',[
 PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$name='wellness_clinic_test_'.bin2hex(random_bytes(6));$pdo->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$pdo->exec("USE `$name`");
$schema=file_get_contents(dirname(__DIR__,2).'/database/schema.sql');$pdo->exec(preg_replace('/^(CREATE DATABASE|USE ).*;\r?$/m','',$schema));
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/005_customer_onboarding.sql'));
$pdo->exec(file_get_contents(dirname(__DIR__,2).'/database/migrations/039_separate_clinic_portals.sql'));
$pdo->exec("INSERT INTO clinics(id,name) VALUES(1,'Willow Virtual'); INSERT INTO locations(clinic_id,name) VALUES(1,'Willow Virtual');
 INSERT INTO users(id,clinic_id,email,display_name,user_type,status) VALUES(1,1,'admin@example.test','Operator','staff','active');
 INSERT INTO user_roles(user_id,role_id) SELECT 1,id FROM roles WHERE code='super_admin';
 INSERT INTO identity_links(user_id,provider,tenant_id,provider_subject) VALUES(1,'microsoft','trusted-tenant','operator-subject');");
$config=new Config('test',false,'test-key',[],'127.0.0.1',$port,$name,'root','','trusted-tenant','api','scope',300,
 customerOnboardingEnabled:true,customerClinicId:1,clinicHostMap:['willow.test'=>1],clinicManagementEnabled:true);
$database=new Database($config);(new ReflectionProperty(Database::class,'connection'))->setValue($database,$pdo);
$audit=new AuditLogger($database);$manage=new ClinicManagementService($database,$audit,$config);
$actor=new AuthContext(1,1,'operator-subject','admin@example.test','Operator','staff',['super_admin']);
$checks=0;
$check=function(bool $ok,string $why='Isolation assertion failed')use(&$checks){if(!$ok)throw new RuntimeException($why);$checks++;};
$deny=function(callable $fn,int $status)use($check){try{$fn();}catch(ApiException $e){$check($e->status===$status,$e->errorCode);return;}throw new RuntimeException('Expected denial');};
$manage->configure($actor,1,['name'=>'Willow Wellness Virtual','portal_host'=>'willow.test'],'test');
$clinic=$manage->create($actor,['name'=>"Livin Lively",'portal_host'=>'livin.test','website_url'=>'https://livinlively.ca','initial_location_name'=>'Holland Landing'],'test');$id=(int)$clinic['id'];
$check($id!==1);
$check(count($manage->list($actor)['items'])===2);
$deny(fn()=>$manage->create($actor,['name'=>'Bad','portal_host'=>'willow.test','initial_location_name'=>'Main'],'test'),409);
$deny(fn()=>$manage->create($actor,['name'=>'Duplicate','portal_host'=>'livin.test','initial_location_name'=>'Main'],'test'),409);
$check((int)$pdo->query('SELECT COUNT(*) FROM clinics')->fetchColumn()===2,'Duplicate provisioning must roll back');
$deny(fn()=>$manage->configure($actor,$id,['name'=>'Wrong','portal_host'=>'other.test'],'test'),404);
$deny(fn()=>$manage->create(new AuthContext(1,1,'','','','staff',['clinic_admin']),['name'=>'Wrong','portal_host'=>'other.test'],'test'),403);
$context=fn(string $host)=>ClinicContext::resolve($config,$database,new Request('GET','/api/v1/locations',['clinic_id'=>1],['host'=>$host,'x-forwarded-host'=>'willow.test'],[],'test'));
$willow=$context('willow.test');$livin=$context('LIVIN.TEST.');$check($livin->clinicId===$id && $willow->clinicId===1);
$identity=new VerifiedIdentity('entra-workforce','https://login.microsoftonline.com/trusted-tenant/v2.0','operator-subject','trusted-tenant',['super_admin']);
$admin=(new StaffMembershipResolver($database))->resolve($identity,$livin);$check($admin->userId!==1 && $admin->clinicId===$id);
$key=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);if(!$key)throw new RuntimeException('RSA test key unavailable');
$rsa=openssl_pkey_get_details($key)['rsa'];$jwk=['kty'=>'RSA','kid'=>'test','n'=>JWT::urlsafeB64Encode($rsa['n']),'e'=>JWT::urlsafeB64Encode($rsa['e'])];
$auth=new EntraAuthenticator($config,$database,fn()=>['keys'=>[$jwk]]);
$token=JWT::encode(['iss'=>$identity->issuer,'tid'=>'trusted-tenant','aud'=>'api','oid'=>'operator-subject','scp'=>'scope','roles'=>['Wellness.SuperAdmin'],'iat'=>time()-10,'nbf'=>time()-10,'exp'=>time()+300],$key,'RS256','test');
$check($auth->authenticateForClinic($token,$livin)->userId===$admin->userId);
$check($auth->authenticateForClinic($token,$willow)->userId===1);
$deny(fn()=>$willow->assertActor($admin),403);
$service=new AdminService($database,$audit);
$service->createLocation($admin,['name'=>'Second Livin location','timezone'=>'America/Toronto'],'test');
$check(count($service->locations($admin))===2 && count($service->locations($actor))===1);
$check(count((new CatalogService($database,1))->locations())===1);
$check(count((new CatalogService($database,$id))->locations())===2);
$deny(fn()=>$service->updateLocation($actor,(int)$service->locations($admin)[0]['id'],['name'=>'Hijack','timezone'=>'America/Toronto'],'test'),404);
$check(ClinicPortalUrl::resolve($pdo,$id,'https://wrong.test/client',true)==='https://livin.test/client');
$deny(fn()=>$context('unknown.test'),404);
$pdo->exec("INSERT INTO clinics(name) VALUES('Unrelated clinic')");$check(count($manage->list($actor)['items'])===2,'Management list must not reveal unrelated clinics');

$a=new CustomerOnboarding($pdo,$config,1);$b=new CustomerOnboarding($pdo,$config,$id);
$claims=['iss'=>'trusted-client','sub'=>'one-client','tid'=>'tenant','oid'=>'11111111-1111-1111-1111-111111111111'];
$start=function(CustomerOnboarding $service)use($claims){$nonce=$service->challenge('127.0.0.1')['nonce'];return $service->startSession($claims,$claims+['nonce'=>$nonce,'auth_time'=>time()],'test');};
$sessionA=$start($a);$sessionB=$start($b);$identityA=$a->session($claims,$sessionA['session_token'])['identity_id'];$identityB=$b->session($claims,$sessionB['session_token'])['identity_id'];$check($identityA===$identityB);
$deny(fn()=>$b->session($claims,$sessionA['session_token']),401);
$b->logout($sessionA['session_token'],'test');$check($a->session($claims,$sessionA['session_token'])['identity_id']===$identityA,'Other clinic logout must not revoke a session');
$nonce=$a->challenge('127.0.0.1')['nonce'];$deny(fn()=>$b->startSession($claims,$claims+['nonce'=>$nonce,'auth_time'=>time()],'test'),401);
$body=['given_name'=>'Shared','family_name'=>'Identity','email'=>'same@example.test','phone'=>'555-0100','address'=>['address_line1'=>'1 Test St','city'=>'Test City','province'=>'ON','postal_code'=>'A1A 1A1','country'=>'Canada']];
$a->register($identityA,$body,'test');$b->register($identityB,$body,'test');
$clientA=$a->bookingActor($identityA);$clientB=$b->bookingActor($identityB);$check($clientA->userId!==$clientB->userId && $clientA->clinicId===1 && $clientB->clinicId===$id);
$check((int)$pdo->query('SELECT COUNT(*) FROM customer_client_links')->fetchColumn()===2);
$deny(fn()=>(new ClientService($database,$audit))->get($actor,$clientB->userId,'test'),404);
$deny(fn()=>(new ClientService($database,$audit))->get($admin,$clientA->userId,'test'),404);
$pdo->prepare("UPDATE staff_memberships SET status='revoked' WHERE local_user_id=?")->execute([$admin->userId]);
$deny(fn()=>(new StaffMembershipResolver($database))->resolve($identity,$livin),403);
$deny(fn()=>$auth->authenticateForClinic($token,$livin),403);
$check((new StaffMembershipResolver($database))->resolve($identity,$willow)->userId===1);
echo "$checks real MariaDB clinic and location isolation checks passed. Synthetic database retained: $name\n";
