<?php
declare(strict_types=1);
// Synthetic local-only rehearsal. Never loads the application's .env or touches hosted data.
require dirname(__DIR__,2).'/vendor/autoload.php';
use Wellness\Auth\AuthContext;
use Wellness\Auth\VerifiedIdentity;
use Wellness\Auth\StaffMembershipResolver;
use Wellness\ClinicContext;
use Wellness\Config;
use Wellness\Database;
use Wellness\Http\ApiException;
use Wellness\Service\AuditLogger;
use Wellness\Service\StaffInvitationService;

if(getenv('STAFF_INVITATION_TEST_ALLOW_CREATE')!=='true')throw new RuntimeException('Set STAFF_INVITATION_TEST_ALLOW_CREATE=true for a synthetic local database.');
$port=(int)(getenv('STAFF_INVITATION_TEST_PORT')?:13317);
$pdo=new PDO("mysql:host=127.0.0.1;port=$port;charset=utf8mb4",getenv('STAFF_INVITATION_TEST_USER')?:'root',getenv('STAFF_INVITATION_TEST_PASSWORD')?:'',[
 PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$name='wellness_staff_invite_test_'.bin2hex(random_bytes(6));
$pdo->exec("CREATE DATABASE `$name` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");$pdo->exec("USE `$name`");
echo "Synthetic database retained for inspection: $name\n";
$schema=file_get_contents(dirname(__DIR__,2).'/database/schema.sql');
$pdo->exec(preg_replace('/^(CREATE DATABASE|USE ).*;\r?$/m','',$schema));
$pdo->exec("INSERT INTO clinics(id,name) VALUES(1,'Synthetic Clinic A'),(2,'Synthetic Clinic B');
 INSERT INTO locations(id,clinic_id,name) VALUES(1,1,'Main A'),(2,2,'Main B');
 INSERT INTO users(id,clinic_id,email,display_name,user_type,status) VALUES(1,1,'admin@example.test','Admin','staff','active'),(2,1,'legacy@example.test','Legacy','staff','active');
 INSERT INTO user_roles(user_id,role_id,assigned_by) SELECT 1,id,1 FROM roles WHERE code='super_admin';
 INSERT INTO practitioners(user_id,discipline) VALUES(2,'Massage');");
$config=new Config('test',false,'test',[],'127.0.0.1',$port,$name,'','','workforce','workforce-api','scope',300,
 clinicHostMap:['a.test'=>1,'b.test'=>2],staffInvitationsEnabled:true);
$database=new Database($config);(new ReflectionProperty(Database::class,'connection'))->setValue($database,$pdo);
$service=new StaffInvitationService($database,$config,new AuditLogger($database));
$admin=new AuthContext(1,1,'admin','admin@example.test','Admin','staff',['super_admin']);
$checks=0;
$check=function(bool $ok)use(&$checks){if(!$ok)throw new RuntimeException('Integration assertion failed');$checks++;};
$deny=function(callable $action,string $code)use($check){try{$action();}catch(ApiException $e){$check($e->errorCode===$code);return;}throw new RuntimeException('Expected denial');};
$details=['recipient_email'=>'new@example.test','given_name'=>'New','family_name'=>'Practitioner','discipline'=>'Massage','location_id'=>1];
$deny(fn()=>$service->create($admin,array_replace($details,['location_id'=>2]),'test'),'location_not_found');
$invite=$service->create($admin,$details,'test');
$check($pdo->query('SELECT token_hash FROM staff_invitations')->fetchColumn()===hash('sha256',$invite['token']));
$identity=new VerifiedIdentity('entra-external-staff','https://trusted.test','subject-A','tenant');
$claim=['token'=>$invite['token'],'claimant_name'=>'New Practitioner'];
$deny(fn()=>$service->claim(2,$identity,$claim,'test'),'invitation_not_found');
$resolver=new StaffMembershipResolver($database);$clinic=ClinicContext::forHost($config,'a.test');
$deny(fn()=>$resolver->resolve($identity,$clinic),'membership_required');
$result=$service->claim(1,$identity,$claim,'test');
$check($service->claim(1,$identity,$claim,'test')===$result);
$check((int)$pdo->query('SELECT COUNT(*) FROM staff_memberships')->fetchColumn()===0);
$approval=['recipient_verified'=>true,'verification_code'=>$result['verification_code']];
$deny(fn()=>$service->approve($admin,$invite['id'],array_replace($approval,['verification_code'=>'WRONG']),'test'),'recipient_verification_required');
$accepted=$service->approve($admin,$invite['id'],$approval,'test');
$actor=$resolver->resolve($identity,$clinic);$check($actor->userId===$accepted['user_id']&&$actor->roles===['practitioner']&&$actor->permissions===[]);
$check((int)$pdo->query('SELECT COUNT(*) FROM practitioners')->fetchColumn()===2);
$deny(fn()=>$resolver->resolve($identity,ClinicContext::forHost($config,'b.test')),'membership_required');
$deny(fn()=>$service->approve($admin,$invite['id'],$approval,'test'),'invitation_unavailable');
$check((int)$pdo->query('SELECT COUNT(*) FROM staff_memberships')->fetchColumn()===1);
$pdo->exec("UPDATE staff_memberships SET status='revoked'");
$deny(fn()=>$resolver->resolve($identity,$clinic),'membership_required');
$again=$service->create($admin,array_replace($details,['recipient_email'=>'other@example.test']),'test');
$againClaim=$service->claim(1,$identity,['token'=>$again['token'],'claimant_name'=>'New Practitioner'],'test');
$deny(fn()=>$service->approve($admin,$again['id'],['recipient_verified'=>true,'verification_code'=>$againClaim['verification_code']],'test'),'membership_exists');
$check($pdo->query('SELECT status FROM staff_memberships')->fetchColumn()==='revoked');
$check((int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn()===3);
$legacy=$service->create($admin,array_replace($details,['recipient_email'=>'legacy@example.test','existing_user_id'=>2]),'test');
$legacyIdentity=new VerifiedIdentity('entra-external-staff','https://trusted.test','subject-legacy','tenant');
$legacyClaim=$service->claim(1,$legacyIdentity,['token'=>$legacy['token'],'claimant_name'=>'Legacy Practitioner'],'test');
$legacyApproval=$service->approve($admin,$legacy['id'],['recipient_verified'=>true,'verification_code'=>$legacyClaim['verification_code']],'test');
$check($legacyApproval['user_id']===2&&(int)$pdo->query('SELECT COUNT(*) FROM users')->fetchColumn()===3);
$deny(fn()=>$service->create($admin,array_replace($details,['existing_user_id'=>2]),'test'),'membership_exists');
$revoked=$service->create($admin,array_replace($details,['recipient_email'=>'revoked@example.test']),'test');$service->revoke($admin,$revoked['id'],'test');
$deny(fn()=>$service->claim(1,$identity,['token'=>$revoked['token'],'claimant_name'=>'New Practitioner'],'test'),'invitation_unavailable');
$expired=$service->create($admin,array_replace($details,['recipient_email'=>'expired@example.test']),'test');
$pdo->exec('UPDATE staff_invitations SET expires_at=UTC_TIMESTAMP()-INTERVAL 1 MINUTE WHERE id='.(int)$expired['id']);
$deny(fn()=>$service->claim(1,$identity,['token'=>$expired['token'],'claimant_name'=>'New Practitioner'],'test'),'invitation_unavailable');
echo "$checks real MySQL staff invitation checks passed.\n";
