import { useEffect, useMemo, useRef, useState, type FormEvent } from 'react';
import { Alert, Button, CircularProgress, Divider, Grid, MenuItem, Paper, Stack, Step, StepLabel, Stepper, TextField, Typography } from '@mui/material';
import { useTranslation } from 'react-i18next';
import { formatCad, formatDateTime } from '../i18n/format';
import { AddressEntry, type AddressValue } from '../shared/AddressEntry';
import { useUnsavedChanges } from '../shared/UnsavedChanges';
import { customerFetch, CustomerRequestError } from './session';
import { customerBookingIntent } from './bookingIntent';

type Combination = { location_id: number; location_name: string; timezone: string; service_id: number; service_name: string; requires_room: number; offers_mobile: number; offers_clinic: number; travel_buffer_minutes: number; mobile_fee_cents: number; base_price_cents: number; practitioner_id: number; practitioner_name: string; duration_option_id: number; duration_minutes: number };
type Room = { id: number; name: string; location_id: number };
type Slot = { duration_option_id: number; starts_at: string; ends_at: string; available_room_ids: number[] };
type Destination = AddressValue & { instructions: string };
type Coverage = { destination: Destination; distance_km: number; radius_km: number; token: string };
type Payload = { delivery_mode: 'clinic'|'mobile'; destination?: Destination; address_validation_token?: string; quoted_base_price_cents: number; quoted_mobile_fee_cents: number; location_id: number; service_id: number; practitioner_id: number; duration_option_id: number; starts_at: string; room_id?: number; idempotency_key: string };

const emptyDestination = (): Destination => ({ address_line1:'', address_line2:'', city:'', province:'Ontario', postal_code:'', country:'Canada', instructions:'' });
const unique = (rows: Combination[], key: keyof Combination) => [...new Map(rows.map(row => [String(row[key]), row])).values()];
const today = (zone: string) => new Intl.DateTimeFormat('en-CA', { timeZone: zone, year:'numeric', month:'2-digit', day:'2-digit' }).format(new Date());

export function CustomerBooking({ cancel, complete }: { cancel: () => void; complete: (id: number) => void }) {
  const { t, i18n } = useTranslation();
  const [intent] = useState(customerBookingIntent);
  const [options,setOptions]=useState<Combination[]>([]),[rooms,setRooms]=useState<Room[]>([]);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [step,setStep]=useState(0),[mode,setMode]=useState<'clinic'|'mobile'>(intent?.delivery_mode??'mobile');
  const [location,setLocation]=useState(intent?.location_id??''),[service,setService]=useState(intent?.service_id??''),[practitioner,setPractitioner]=useState(intent?.practitioner_id??''),[duration,setDuration]=useState(intent?.duration_option_id??''),[date,setDate]=useState(''),[room,setRoom]=useState('');
  const [slots,setSlots]=useState<Slot[]>([]),[slot,setSlot]=useState<Slot|null>(null),[searched,setSearched]=useState(false);
  const [destination,setDestination]=useState<Destination>(emptyDestination),[coverage,setCoverage]=useState<Coverage|null>(null),[coverageBusy,setCoverageBusy]=useState(false),[addressLoaded,setAddressLoaded]=useState(false);
  const [pending,setPending]=useState<Payload|null>(null); const pendingRef=useRef<Payload|null>(null), sending=useRef(false);
  const eligible=useMemo(()=>options.filter(row=>Number(mode==='mobile'?row.offers_mobile:row.offers_clinic)),[mode,options]);
  const locationRows=eligible.filter(row=>String(row.location_id)===location), serviceRows=locationRows.filter(row=>String(row.service_id)===service), practitionerRows=serviceRows.filter(row=>String(row.practitioner_id)===practitioner);
  const selected=practitionerRows.find(row=>String(row.duration_option_id)===duration);
  const timezone=options.find(row=>String(row.location_id)===location)?.timezone??'America/Toronto';
  const needsRoom=mode==='clinic'&&Boolean(Number(selected?.requires_room)), mobileFee=mode==='mobile'?Number(selected?.mobile_fee_cents??0):0;
  const addressComplete=(['address_line1','city','province','postal_code','country'] as const).every(key=>destination[key].trim());
  const addressReady=mode==='clinic'||(addressComplete&&Boolean(coverage));
  useUnsavedChanges(Boolean(location||service||practitioner||duration||date||slot||room||pending));

  useEffect(()=>{const controller=new AbortController();setLoading(true);setError('');Promise.all([
    customerFetch('/booking-options',{signal:controller.signal}),customerFetch('/profile',{signal:controller.signal}),
  ]).then(([booking,profile])=>{if(controller.signal.aborted)return;setOptions(booking.combinations);setRooms(booking.rooms);setLocation(current=>current||(booking.default_location_id?String(booking.default_location_id):''));if(profile.address)setDestination({...emptyDestination(),...profile.address,instructions:profile.address.instructions??''});setAddressLoaded(true);}).catch(cause=>{if(!controller.signal.aborted)setError(cause instanceof Error?cause.message:t('Unable to load booking options.'));}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[t]);
  useEffect(()=>{if(intent&&location&&!date)setDate(new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(intent.starts_at)));},[date,intent,location,timezone]);
  useEffect(()=>{if(location)return;const choices=unique(eligible,'location_id');if(choices.length===1)setLocation(String(choices[0].location_id));},[eligible,location]);
  const clearSlots=()=>{setSlots([]);setSlot(null);setRoom('');setSearched(false);};
  const resetCare=(nextMode:'clinic'|'mobile')=>{setMode(nextMode);setLocation('');setService('');setPractitioner('');setDuration('');setDate('');setCoverage(null);clearSlots();};
  const validateCoverage=async()=>{if(!selected||!addressComplete)return;setCoverageBusy(true);setCoverage(null);setError('');clearSlots();try{const result=await customerFetch('/address-coverage/validate',{method:'POST',body:JSON.stringify({location_id:Number(location),service_id:Number(service),practitioner_id:Number(practitioner),destination})});setDestination(result.destination);setCoverage(result);}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to validate this address.'));}finally{setCoverageBusy(false);}};
  const findSlots=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;setBusy(true);setError('');clearSlots();try{const params=new URLSearchParams({location_id:location,service_id:service,practitioner_id:practitioner,delivery_mode:mode,date_from:date,date_to:date});const result=await customerFetch(`/availability?${params}`);const available=result.availability.filter((item:Slot)=>Number(item.duration_option_id)===Number(duration));setSlots(available);const preferred=intent?available.find((item:Slot)=>Date.parse(item.starts_at)===Date.parse(intent.starts_at)):null;if(preferred){setSlot(preferred);setRoom(preferred.available_room_ids.length===1?String(preferred.available_room_ids[0]):'');}setSearched(true);}catch(cause){setError(cause instanceof Error?cause.message:t('Unable to load times.'));}finally{setBusy(false);}};
  const confirm=async()=>{if(sending.current||!selected||!slot)return;sending.current=true;setBusy(true);setError('');const payload=pendingRef.current??{delivery_mode:mode,...(mode==='mobile'?{destination,address_validation_token:coverage!.token}:{}),quoted_base_price_cents:Number(selected.base_price_cents),quoted_mobile_fee_cents:mobileFee,location_id:Number(location),service_id:Number(service),practitioner_id:Number(practitioner),duration_option_id:Number(duration),starts_at:slot.starts_at,...(needsRoom?{room_id:Number(room)}:{}),idempotency_key:crypto.randomUUID()};pendingRef.current=payload;setPending(payload);try{const result=await customerFetch('/appointments',{method:'POST',body:JSON.stringify(payload)});pendingRef.current=null;setPending(null);complete(result.id);}catch(cause){if(cause instanceof CustomerRequestError&&cause.status>=400&&cause.status<500){pendingRef.current=null;setPending(null);setStep(1);clearSlots();if(cause.code.includes('coverage'))setCoverage(null);}setError(cause instanceof Error?cause.message:t('Unable to confirm appointment.'));}finally{sending.current=false;setBusy(false);}};
  const select=(label:string,value:string,rows:Combination[],key:keyof Combination,name:(row:Combination)=>string,change:(value:string)=>void)=><TextField fullWidth required select label={label} value={value} onChange={event=>change(event.target.value)}>{unique(rows,key).map(row=><MenuItem key={String(row[key])} value={String(row[key])}>{name(row)}</MenuItem>)}</TextField>;
  const display=(value:string)=>formatDateTime(value,i18n.resolvedLanguage,{timeZone:timezone,dateStyle:'medium',timeStyle:'short'});
  return <Paper variant="outlined" sx={{p:{xs:2,md:3}}}>
    <Typography variant="h5" mb={1}>{t('New appointment')}</Typography><Typography color="text.secondary" mb={3}>{t('Choose a service, practitioner, and visit type. No time is reserved until you confirm.')}</Typography>
    <Stepper activeStep={step} alternativeLabel sx={{mb:3}}>{['Choose care','Available time','Review and confirm'].map(label=><Step key={label}><StepLabel>{t(label)}</StepLabel></Step>)}</Stepper>
    {error&&<Alert severity="error" sx={{mb:2}}>{error}</Alert>}
    {loading?<CircularProgress aria-label={t('Loading booking options')}/>:options.length===0?<Alert severity="info">{t('No booking combinations are configured. Check active services, durations, practitioners, and location assignments in administration.')}</Alert>:<>
      {step===0&&<Stack spacing={3}>
        <TextField select label={t('Visit type')} value={mode} onChange={event=>resetCare(event.target.value as 'clinic'|'mobile')}><MenuItem value="mobile">{t('On-Site (client location)')}</MenuItem><MenuItem value="clinic">{t('In clinic')}</MenuItem></TextField>
        {eligible.length===0&&<Alert severity="info">{t('No services are configured for this visit type. Enable it under Service assignments and choose a base location.')}</Alert>}
        <Grid container spacing={2}><Grid size={{xs:12,sm:6}}>{select(t('Base location / service area'),location,eligible,'location_id',row=>row.location_name,value=>{setLocation(value);setService('');setPractitioner('');setDuration('');setCoverage(null);clearSlots();})}</Grid><Grid size={{xs:12,sm:6}}>{select(t('Service'),service,locationRows,'service_id',row=>row.service_name,value=>{setService(value);setPractitioner('');setDuration('');setCoverage(null);clearSlots();})}</Grid><Grid size={{xs:12,sm:6}}>{select(t('Practitioner'),practitioner,serviceRows,'practitioner_id',row=>row.practitioner_name,value=>{setPractitioner(value);setDuration('');setCoverage(null);clearSlots();})}</Grid><Grid size={{xs:12,sm:6}}>{select(t('Duration'),duration,practitionerRows,'duration_option_id',row=>t('{{minutes}} minutes — {{price}}',{minutes:row.duration_minutes,price:formatCad(Number(row.base_price_cents),i18n.resolvedLanguage)}),value=>{setDuration(value);clearSlots();})}</Grid></Grid>
        {mode==='mobile'&&<Stack spacing={2}><Typography variant="h6">{t('Visit address')}</Typography>{addressLoaded&&addressComplete&&<Alert severity="info">{t('The saved client address is loaded. You can replace it using Google address suggestions. Changes apply only to this appointment.')}</Alert>}<AddressEntry required showInstructions disabled={coverageBusy} value={destination} onChange={value=>{setDestination({...value,instructions:value.instructions??''});setCoverage(null);}}/><Alert severity="info">{t('Google validates the address and calculates driving distance from the selected base location. The address must be within the configured On-Site service area.')}</Alert><Button variant="outlined" disabled={!selected||!addressComplete||coverageBusy} onClick={()=>void validateCoverage()}>{t(coverageBusy?'Validating address…':'Validate address and coverage')}</Button>{coverage&&<Alert severity="success">{t('Address confirmed: {{distance}} km driving distance ({{radius}} km limit).',{distance:coverage.distance_km,radius:coverage.radius_km})}</Alert>}</Stack>}
        <Button variant="contained" disabled={!selected||!addressReady} onClick={()=>{setDate(date||today(timezone));setStep(1);}}>{t('Find a time')}</Button>
      </Stack>}
      {step===1&&<Stack spacing={2}><Typography>{t('Availability in {{timezone}}. Choose a day to see current openings.',{timezone})}</Typography><Stack component="form" direction={{xs:'column',sm:'row'}} gap={2} onSubmit={findSlots}><TextField required type="date" label={t('Appointment date')} value={date} disabled={busy} InputLabelProps={{shrink:true}} inputProps={{min:today(timezone)}} onChange={event=>{setDate(event.target.value);clearSlots();}}/><Button type="submit" variant="outlined" disabled={busy||!date}>{t(busy?'Searching…':'Find times')}</Button></Stack>{searched&&slots.length===0&&<Alert severity="info">{t('No bookable times on this day. Try another day or check working hours and room assignments.')}</Alert>}<Stack direction="row" flexWrap="wrap" gap={1}>{slots.map(item=><Button key={item.starts_at} variant={slot?.starts_at===item.starts_at?'contained':'outlined'} onClick={()=>{setSlot(item);setRoom(item.available_room_ids.length===1?String(item.available_room_ids[0]):'');}}>{display(item.starts_at)}</Button>)}</Stack>{slot&&needsRoom&&<TextField select required label={t('Available room')} value={room} onChange={event=>setRoom(event.target.value)}>{slot.available_room_ids.map(id=><MenuItem key={id} value={String(id)}>{rooms.find(item=>Number(item.id)===Number(id))?.name??t('Room {{number}}',{number:id})}</MenuItem>)}</TextField>}<Button variant="contained" disabled={!slot||(needsRoom&&!room)} onClick={()=>setStep(2)}>{t('Review appointment')}</Button></Stack>}
      {step===2&&selected&&slot&&<Stack spacing={2}><Typography variant="h6">{selected.service_name}</Typography><Typography>{t('{{minutes}} minutes',{minutes:selected.duration_minutes})} · {selected.practitioner_name}</Typography><Typography>{display(slot.starts_at)} – {display(slot.ends_at)} ({timezone})</Typography><Typography>{selected.location_name}{room?` · ${rooms.find(item=>String(item.id)===room)?.name??t('Room {{number}}',{number:room})}`:''}</Typography><Typography>{t(mode==='mobile'?'On-Site (client location)':'In clinic')}</Typography><Typography>{t('Treatment: {{treatment}} · On-Site surcharge: {{mobile}} · Subtotal: {{subtotal}} CAD',{treatment:formatCad(Number(selected.base_price_cents),i18n.resolvedLanguage),mobile:formatCad(mobileFee,i18n.resolvedLanguage),subtotal:formatCad(Number(selected.base_price_cents)+mobileFee,i18n.resolvedLanguage)})}</Typography><Alert severity="info">{t('Prices shown are before applicable taxes. Tax calculation and invoicing are not yet enabled.')}</Alert><Divider/><Typography color="text.secondary">{t('Availability is checked again when you confirm. We will email your confirmation; keep the appointment number for reference.')}</Typography>{pending&&!busy&&<Alert severity="warning">{t('Confirmation could not be verified. Retry this same request to safely retrieve or complete it. Check the appointment list before starting a different booking.')}</Alert>}<Button variant="contained" disabled={busy} onClick={()=>void confirm()}>{t(busy?'Confirming…':pending?'Retry confirmation':'Confirm appointment')}</Button></Stack>}
    </>}
    <Stack direction="row" justifyContent="space-between" mt={3}><Button disabled={busy||Boolean(pending)} onClick={cancel}>{t('Cancel')}</Button>{step>0&&<Button disabled={busy||Boolean(pending)} onClick={()=>setStep(value=>value-1)}>{t('Back')}</Button>}</Stack>
  </Paper>;
}
